"""dispatch_load — the general Bronze->Silver dispatcher.

TODO.md priority 2 / CLAUDE.md "Next session starts here" items #1-#2.
Before this module, four separate mechanisms existed with nothing naming
which `doc_type_code` uses which:

    PDF_EXTRACTION      src/extraction/registry.py -> src/extraction/dispatch.py
    SALES_REGISTER      src/silver/sales_register.py (SALES_REGISTER only)
    REGISTER_LOADER     src/silver/registers/catalog.py's spec_for -> RegisterLoader
    ARCHETYPE1_PROMOTE  src/silver/promote.py's SilverPromotionService

The routing decision is registry DATA (`platform_ref.document_type
.dispatch_mechanism`, shared migration 017, generated by
`scripts/gen_registry_seed.py` from `registry/document_types.csv`), the same
"the twelfth type is a CSV row, not a code change" idiom `field_contract` and
`extraction_spec` already give the other two per-type registry columns.
Adding a document type under an EXISTING mechanism is a CSV row. Adding a
genuinely new mechanism (a future archetype-3 entitlement-promotion path, for
instance) still needs one new branch below, once — that part cannot be data,
because the code to do the write has to exist somewhere.

Called synchronously, in-process, from `POST /artefacts/{id}/trigger`
(`src/api/routes_ingest.py`). This does not weaken HANDOFF-2026-08-07.md's
"the upsert must NOT go behind an API" — that argument is about never putting
the loader itself behind a SECOND, remote HTTP hop (per-row HTTP, a broken
`SET LOCAL ROLE` transaction boundary, a non-atomic supersede+manifest write);
calling straight into `RegisterLoader`/`SilverPromotionService`/
`run_extraction` from within the same process, same transaction, is exactly
"stays in-process psycopg."
"""

from __future__ import annotations

import datetime as dt
import uuid
from collections.abc import Callable
from dataclasses import dataclass
from typing import cast

from src.core.pool import TenantScopedPool
from src.core.tenant import Role, TenantContext
from src.dispatch.manifest import read_batch_manifest
from src.events.publisher import BatchPublisherPort
from src.extraction.base import DocumentExtractor
from src.extraction.dispatch import run_extraction
from src.extraction.reader import PdfTextPort
from src.extraction.registry import build_extractor_registry
from src.provisioning.objectstore import ObjectStorePort
from src.silver.gstn_returns import GstnReturnLoaderPort
from src.silver.gstn_returns.gstr2b import Gstr2bLoader
from src.silver.gstn_returns.gstr3b import Gstr3bLoader
from src.silver.promote import SilverPromotionService
from src.silver.registers.catalog import spec_for
from src.silver.registers.loader import RegisterLoader
from src.silver.sales_register import SalesRegisterLoader

#: Mirrors scripts/gen_registry_seed.py's DISPATCH_MECHANISMS — kept as a
#: separate literal rather than imported, since the generator is a build-time
#: script (imports src.silver.promote etc. for validation) and this is a
#: runtime module; importing the script here would run its module-level code
#: for no benefit. shared migration 017's CHECK constraint is the ultimate
#: source of truth; a value outside this set could only reach the table by
#: bypassing both.
_PDF_EXTRACTION = "PDF_EXTRACTION"
_SALES_REGISTER = "SALES_REGISTER"
_REGISTER_LOADER = "REGISTER_LOADER"
_ARCHETYPE1_PROMOTE = "ARCHETYPE1_PROMOTE"
_GSTN_JSON_PROMOTE = "GSTN_JSON_PROMOTE"

#: doc_type_code -> loader class for GSTN_JSON_PROMOTE. Unlike the other four
#: mechanisms, this one is NOT shape-uniform across the types it will
#: eventually serve (D3, HANDOFF-2026-08-19-categoryB.md) — GSTR_1/9/9C
#: will each need their own loader class, the same "bespoke Python per type"
#: shape `src/extraction/register_types.py` already uses for archetype 2.
#: `GSTR_2B`/`GSTR_3B` are built so far.
_GSTN_RETURN_LOADERS: dict[str, Callable[[TenantScopedPool], GstnReturnLoaderPort]] = {
    "GSTR_2B": Gstr2bLoader,
    "GSTR_3B": Gstr3bLoader,
}


class NoDispatchMechanismError(ValueError):
    """`doc_type_code` has no `dispatch_mechanism` — either this type is not
    upload-triggered at all (a Stream A polled return, for instance), or it
    is upload-triggered but no loader/extractor has been built for it yet
    (an empty cell is a real, honest "not yet", not a bug)."""


class MissingDispatchFieldError(ValueError):
    """The resolved mechanism needs a field (`gstin`, `period_start`,
    `period_end`) that this call did not supply. Only PDF_EXTRACTION needs
    none of these — a PDF is a single dated instrument, not a period
    export."""


@dataclass(frozen=True, slots=True)
class DispatchOutcome:
    """What one dispatched trigger produced, normalised across all four
    mechanisms so `POST /artefacts/{id}/trigger` can report one shape
    regardless of which mechanism actually ran.

    `detail` stays the mechanism's own outcome type (`BatchManifest` /
    `RegisterOutcome` / `UpsertOutcome` / the `run_extraction` tuple) rather
    than being flattened further — the trigger route reports a summary from
    it, but nothing here should force every mechanism's richer detail into a
    lowest-common-denominator shape.
    """

    mechanism: str
    batch_id: uuid.UUID | None
    written: bool
    status: str
    """SilverReader.artefact_outcome's vocabulary (ACCEPTED/PARTIAL/
    QUARANTINED) — a dispatched trigger is never PENDING, since dispatch_load
    only returns after the write (or quarantine) already committed."""
    detail: object


async def dispatch_load(
    ctx: TenantContext,
    pool: TenantScopedPool,
    *,
    ingest_id: uuid.UUID,
    entity_id: uuid.UUID,
    doc_type_code: str,
    data: bytes,
    content_format: str,
    period_start: dt.date | None = None,
    period_end: dt.date | None = None,
    gstin: str | None = None,
    store: ObjectStorePort | None = None,
    ingest_run_id: uuid.UUID | None = None,
    extractor_registry: dict[str, DocumentExtractor] | None = None,
    reader: PdfTextPort | None = None,
    publisher: BatchPublisherPort | None = None,
) -> DispatchOutcome:
    """Resolve `doc_type_code`'s `dispatch_mechanism` and run it.

    `extractor_registry`/`reader` are escape hatches for a caller processing
    many artefacts in one request (skip re-querying the registry / reuse a
    reader that has OCR wired in) — the same trade `run_extraction` and
    `build_extractor_registry` already make; left unset, each is built fresh.

    `publisher`, if given, rings Pipeline 2's Kafka doorbell once the write
    that produced this outcome has committed — see `_publish_if_ready`.
    `publisher=None` (the default) means no doorbell is wired for this
    caller, the same "escape hatch defaults to off" shape `store`/`reader`
    already use here.
    """
    mechanism = await _resolve_mechanism(pool, ctx, doc_type_code)
    if not mechanism:
        raise NoDispatchMechanismError(
            f"{doc_type_code!r} has no dispatch_mechanism — either it is not "
            f"upload-triggered, or no loader/extractor is built for it yet"
        )

    if mechanism == _PDF_EXTRACTION:
        registry = (
            extractor_registry
            if extractor_registry is not None
            else await build_extractor_registry(pool, ctx, store=store)
        )
        outcome, write_result = await run_extraction(
            ctx, pool,
            ingest_id=ingest_id, entity_id=entity_id, doc_type_code=doc_type_code,
            pdf_bytes=data, ingest_run_id=ingest_run_id, reader=reader, registry=registry,
        )
        return await _publish_if_ready(pool, ctx, publisher, DispatchOutcome(
            mechanism=mechanism, batch_id=write_result.batch_id, written=write_result.written,
            status="ACCEPTED" if write_result.written else "QUARANTINED",
            detail=(outcome, write_result),
        ))

    if mechanism == _SALES_REGISTER:
        _require(gstin=gstin, period_start=period_start, period_end=period_end)
        sales_result = await SalesRegisterLoader(pool).load(
            ctx, entity_id=entity_id, gstin=cast(str, gstin), ingest_id=ingest_id,
            data=data, period_start=cast("dt.date", period_start),
            period_end=cast("dt.date", period_end), ingest_run_id=ingest_run_id,
        )
        return await _publish_if_ready(pool, ctx, publisher, DispatchOutcome(
            mechanism=mechanism, batch_id=sales_result.batch_id, written=True,
            status="ACCEPTED",
            detail=sales_result,
        ))

    if mechanism == _REGISTER_LOADER:
        _require(gstin=gstin, period_start=period_start, period_end=period_end)
        register_result = await RegisterLoader(pool, spec_for(doc_type_code)).load(
            ctx, entity_id=entity_id, gstin=cast(str, gstin), ingest_id=ingest_id,
            data=data, period_start=cast("dt.date", period_start),
            period_end=cast("dt.date", period_end), doc_type_code=doc_type_code,
            ingest_run_id=ingest_run_id, content_format=content_format,
        )
        return await _publish_if_ready(pool, ctx, publisher, DispatchOutcome(
            mechanism=mechanism, batch_id=register_result.batch_id, written=True,
            status="PARTIAL" if register_result.rejected > 0 else "ACCEPTED",
            detail=register_result,
        ))

    if mechanism == _ARCHETYPE1_PROMOTE:
        _require(period_start=period_start, period_end=period_end)
        promotion_manifest = await SilverPromotionService(pool).promote_transaction_documents(
            ctx, document_type=doc_type_code, ingest_id=ingest_id, entity_id=entity_id,
            data=data, period_start=cast("dt.date", period_start),
            period_end=cast("dt.date", period_end), ingest_run_id=ingest_run_id,
        )
        return await _publish_if_ready(pool, ctx, publisher, DispatchOutcome(
            mechanism=mechanism, batch_id=promotion_manifest.batch_id, written=True,
            status="ACCEPTED",
            detail=promotion_manifest,
        ))

    if mechanism == _GSTN_JSON_PROMOTE:
        _require(gstin=gstin, period_start=period_start, period_end=period_end)
        try:
            loader_cls = _GSTN_RETURN_LOADERS[doc_type_code]
        except KeyError:
            raise NoDispatchMechanismError(
                f"{doc_type_code!r} has dispatch_mechanism=GSTN_JSON_PROMOTE but "
                f"no loader is registered for it yet in "
                f"src/dispatch/router.py:_GSTN_RETURN_LOADERS"
            ) from None
        return_outcome = await loader_cls(pool).load(
            ctx, entity_id=entity_id, gstin=cast(str, gstin), ingest_id=ingest_id,
            data=data, period_start=cast("dt.date", period_start),
            period_end=cast("dt.date", period_end), ingest_run_id=ingest_run_id,
        )
        return await _publish_if_ready(pool, ctx, publisher, DispatchOutcome(
            mechanism=mechanism, batch_id=return_outcome.batch_id,
            written=return_outcome.inserted,
            status="ACCEPTED",
            detail=return_outcome,
        ))

    raise AssertionError(f"unreachable dispatch_mechanism {mechanism!r}")


async def _publish_if_ready(
    pool: TenantScopedPool,
    ctx: TenantContext,
    publisher: BatchPublisherPort | None,
    outcome: DispatchOutcome,
) -> DispatchOutcome:
    """Rings Pipeline 2's Kafka doorbell for any outcome that actually wrote
    a batch, generically across all four mechanisms — see
    `src/dispatch/manifest.py`'s module docstring for why one read (keyed on
    `outcome.batch_id`) is enough regardless of which mechanism produced it.

    A QUARANTINED outcome (`batch_id is None`) is never published — there is
    no `ingest_batch` row yet for a consumer to read. `publisher=None` (no
    doorbell wired for this caller) is likewise a no-op, not an error.
    `BatchPublisher.publish` itself never raises (its own docstring), so
    nothing here needs a try/except to preserve "a broker outage degrades
    latency, not correctness."
    """
    if publisher is not None and outcome.batch_id is not None:
        manifest = await read_batch_manifest(pool, ctx, outcome.batch_id)
        await publisher.publish(manifest)
    return outcome


async def _resolve_mechanism(pool: TenantScopedPool, ctx: TenantContext, doc_type_code: str) -> str:
    """Same query idiom `_load_spec`/`build_extractor_registry` already use
    for `field_contract`/`extraction_spec` — read per call, not cached, so a
    corrected `dispatch_mechanism` cell takes effect on the next trigger."""
    async with pool.transaction(ctx, Role.INGEST) as conn:
        row = await (
            await conn.execute(
                "SELECT dispatch_mechanism FROM platform_ref.document_type"
                " WHERE doc_type_code = %s AND in_scope",
                (doc_type_code,),
            )
        ).fetchone()
    if row is None:
        raise NoDispatchMechanismError(
            f"{doc_type_code!r} is not an in-scope document type in the registry"
        )
    return cast(str, row[0])


def _require(**fields: object | None) -> None:
    """Each mechanism's branch above passes only the field names IT needs —
    PDF_EXTRACTION calls this not at all, ARCHETYPE1_PROMOTE omits `gstin` —
    so only those are checked here."""
    missing = [name for name, value in fields.items() if value is None]
    if missing:
        raise MissingDispatchFieldError(
            f"missing required field(s) for this dispatch mechanism: {', '.join(missing)}"
        )
