#!/usr/bin/env python
"""Generate shared migration 042 — the field-constraint seed.

    python scripts/gen_field_constraints.py [--schema t_acme_silver] [--force]

WHY THIS GENERATOR NEEDS A LIVE DATABASE, when `gen_registry_seed.py` does
not. That one projects `registry/document_types.csv`, a file in the repo, so
it runs offline and its output is reproducible from the tree alone. This one
projects `pg_constraint` and `pg_type` — the DDL applied by the tenant
migrations — and there is no offline rendering of those. Parsing the
migration `.sql` files to avoid connecting would mean writing a SQL parser
whose disagreements with Postgres would be silent, which is the failure this
whole change exists to remove.

WHICH TENANT. Any provisioned one. Tenant migrations are templated
(`src/migrate/runner.py`) so every tenant's Silver schema is the same DDL
under a different name, and `make migrate`'s drift check is what keeps that
true. The schema is an explicit argument rather than a lookup so the
generator and the conformance gate can each state which tenant they read.

REGENERATION IS NOT THE FIX WHEN THIS DRIFTS — the same rule
`_write_schema_catalogue` states for 036, for the same reason. 042 is applied
and checksum-pinned; re-running this after a column changes would rewrite it
and break `make migrate`. Carry the delta in a NEW migration. `_emit` refuses
to overwrite a file whose content would change unless `--force` is given, so
a routine run is quiet and any drift is a hard error rather than a silent
rewrite of an applied migration.
"""

from __future__ import annotations

import argparse
import pathlib
import sys
from decimal import Decimal

import psycopg

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from src.catalogue.field_constraints import (
    FieldConstraint,
    SchemaRule,
    derive_field_constraints,
)

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "migrations" / "shared" / "042_document_field_constraints_seed.sql"
DEFAULT_DSN = "postgresql://postgres:postgres@localhost:55432/tenant_db"


def q(value: str) -> str:
    """A SQL string literal. Doubling is the only escaping Postgres needs."""
    return "'" + value.replace("'", "''") + "'"


def _array(values: tuple[str, ...] | None) -> str:
    if not values:
        return "NULL"
    return "ARRAY[" + ", ".join(q(v) for v in values) + "]"


def _num(value: Decimal | None) -> str:
    return "NULL" if value is None else str(value)


def _int(value: int | None) -> str:
    return "NULL" if value is None else str(value)


def _emit(path: pathlib.Path, content: str, *, force: bool) -> None:
    """Refuse to rewrite an applied migration whose content would change.

    Copied in spirit from `gen_registry_seed.py::_emit`, which grew this guard
    after a routine run silently rewrote applied migrations 004 and 023.
    """
    if path.exists() and path.read_text() == content:
        print(f"{path.name}: unchanged")
        return
    if path.exists() and not force:
        raise SystemExit(
            f"{path.name} exists and would CHANGE. It is applied and "
            f"checksum-pinned — regenerating it will break `make migrate`. "
            f"Carry the delta in a NEW migration, or pass --force if you are "
            f"deliberately producing this file for the first time."
        )
    path.write_text(content)
    print(f"{path.name}: written ({len(content.splitlines())} lines)")


def render(constraints: list[FieldConstraint], rules: list[SchemaRule]) -> str:
    out: list[str] = []
    w = out.append
    w("-- =============================================================================")
    w("-- Shared migration 042 — the field-constraint seed.")
    w("--")
    w("-- GENERATED by scripts/gen_field_constraints.py from the LIVE Silver DDL,")
    w("-- via src/catalogue/field_constraints.py. Columns and the rule table:")
    w("-- migration 041 — read its header first, it states what these values are")
    w("-- and why they are derived rather than declared.")
    w("--")
    w("-- Nothing here is hand-written. Every value traces to a pg_constraint row")
    w("-- or a pg_type/attribute fact on a real tenant schema.")
    w("--")
    w("-- DO NOT regenerate this file to fix drift — it is applied and checksum-")
    w("-- pinned. Carry the delta in a NEW migration.")
    w("-- =============================================================================")
    w("")

    carrying = [c for c in constraints if _has_any(c)]
    w(f"-- {len(carrying)} of {len(constraints)} published DERIVED fields carry at")
    w("-- least one constraint. The rest are unconstrained beyond their type and")
    w("-- their NOT NULL, which `data_type` and `required` already publish.")
    w("")

    for c in carrying:
        w("UPDATE platform_ref.document_type_field SET")
        w(f"    sql_domain = {q(c.sql_domain) if c.sql_domain else 'NULL'},")
        w(f"    pattern = {q(c.pattern) if c.pattern else 'NULL'},")
        w(f"    allowed_values = {_array(c.allowed_values)},")
        w(f"    min_value = {_num(c.min_value)},")
        w(f"    max_value = {_num(c.max_value)},")
        w(f"    max_length = {_int(c.max_length)},")
        w(f"    numeric_precision = {_int(c.numeric_precision)},")
        w(f"    numeric_scale = {_int(c.numeric_scale)},")
        w(f"    sql_type = {q(c.sql_type) if c.sql_type else 'NULL'}")
        w(f"  WHERE doc_type_code = {q(c.doc_type_code)}")
        w(f"    AND scope = {q(c.scope)}")
        w(f"    AND field_name = {q(c.field_name)};")
        w("")

    if rules:
        w("INSERT INTO platform_ref.document_type_rule")
        w("    (doc_type_code, constraint_name, expression, columns)")
        w("VALUES")
        w(",\n".join(
            f"    ({q(r.doc_type_code)}, {q(r.constraint_name)}, "
            f"{q(r.expression)}, {_array(r.columns)})"
            for r in rules
        ))
        w(";")
        w("")

    return "\n".join(out)


def _has_any(c: FieldConstraint) -> bool:
    return any(
        v is not None
        for v in (
            c.sql_domain, c.pattern, c.allowed_values, c.min_value, c.max_value,
            c.max_length, c.numeric_precision, c.sql_type,
        )
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--schema", default="t_acme_silver")
    ap.add_argument("--dsn", default=DEFAULT_DSN)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    with psycopg.connect(args.dsn) as conn:
        constraints, rules = derive_field_constraints(conn, args.schema)

    _emit(OUT, render(constraints, rules), force=args.force)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
