#!/usr/bin/env python3
"""Generate the Document Type Registry seed migration from the reviewed CSV.

`registry/document_types.csv` is the source of truth — it is what the CA
engagement team reviews, in the register's own vocabulary. This script compiles
it to SQL.

The generated migration is COMMITTED, not generated at deploy time. Migrations
are checksum-pinned (src/migrate/runner.py); a migration whose content depends
on a file outside the migration chain would break that guarantee silently. Run
this after editing the CSV, and commit both.

    python scripts/gen_registry_seed.py && make migrate

Resolution rules, derived from the CSV rather than hardcoded:

  umbrella  a ref that resolves to several codes (A1.20 -> D1.01-07). Produces
            ref rows only, never a document_type row.
  alias     a ref describing a document already canonical elsewhere
            (D5.06 -> B3.05). Produces a ref row only.
  canonical everything else. Produces a document_type row, its canonical ref
            row, and a non-canonical ref row for each entry in alias_refs.
"""

from __future__ import annotations

import csv
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

# Imported rather than re-implemented: the grammar the runtime enforces at
# ingestion is the grammar a contract is checked against here, so a cell that
# would be rejected at ingestion cannot reach the CSV.
# Same reasoning, for the label:value extraction rule (src/extraction/spec.py)
# — a corrective refactor, 2026-08-11: this used to be 36 hardcoded Python
# ClassVar-only subclasses across src/extraction/*_types.py. See spec.py's
# module docstring for the full story.
from src.extraction.spec import SpecError, parse_extraction_spec  # noqa: E402
from src.silver.contract import ContractError, parse_contract  # noqa: E402

CSV_PATH = ROOT / "registry" / "document_types.csv"
OUT_PATH = ROOT / "migrations" / "shared" / "004_document_registry_seed.sql"
CADENCE_PATH = ROOT / "migrations" / "shared" / "005_document_registry_cadence.sql"
CONTRACT_PATH = ROOT / "migrations" / "shared" / "009_document_registry_field_contract.sql"
EXTRACTION_SPEC_PATH = ROOT / "migrations" / "shared" / "016_extraction_spec.sql"

# A new CSV column becomes a NEW migration, never an edit to an applied one —
# migrations are checksum-pinned (src/migrate/runner.py). 004 is generated from
# the columns it already knew about, so regenerating it after adding a column
# still produces byte-identical output and its checksum holds.

# Tables deliberately shared by several document types. The list is short on
# purpose — see shared migration 013 for why the marketplace reports are on it
# and why nothing else in the 125 qualifies.
SHARED_TABLES = frozenset({"platform_settlement_report"})

UMBRELLA_MARKER = "this ref is an alias"
ALIAS_MARKER = "canonical row is"


def q(s: str) -> str:
    """Single-quote a SQL string literal."""
    return "'" + s.replace("'", "''") + "'"


def arr(sections: str) -> str:
    parts = [p.strip() for p in sections.split(",") if p.strip()]
    return "ARRAY[" + ", ".join(q(p) for p in parts) + "]::text[]"


def _write_cadence(canonical: list[dict[str, str]]) -> None:
    """Emit the refresh_cadence column as its own migration."""
    scoped = [r for r in canonical if r["stream"] != "CORPUS"]
    out: list[str] = []
    w = out.append

    w("-- =============================================================================")
    w("-- Shared migration 005 — refresh_cadence.")
    w("--")
    w("-- GENERATED by scripts/gen_registry_seed.py from registry/document_types.csv.")
    w("--")
    w("-- Doc 4 Section 2: \"In Operational Mode, Mandatory documents are ingested at")
    w("-- onboarding and refreshed at configured intervals.\" This is the column that")
    w("-- drives that. Read from the PLATFORM's refresh perspective, not the")
    w("-- document's own periodicity:")
    w("--")
    w("--   ONE_TIME    requested at onboarding; re-requested only on change or expiry")
    w("--   PERIODIC    re-fetched or re-requested on a schedule")
    w("--   CONTINUOUS  delta-loaded as transactions occur")
    w("--")
    w("-- NULL where in_scope is false: cadence is meaningless for a document this")
    w("-- repo does not ingest.")
    w("-- =============================================================================")
    w("")
    w("ALTER TABLE platform_ref.document_type")
    w("    ADD COLUMN IF NOT EXISTS refresh_cadence text;")
    w("")
    w("UPDATE platform_ref.document_type d")
    w("   SET refresh_cadence = v.cadence")
    w("  FROM (VALUES")
    w(",\n".join(
        f"    ({q(r['doc_type_code'])}, {q(r['refresh_cadence'])})" for r in scoped
    ))
    w("  ) AS v(code, cadence)")
    w(" WHERE d.doc_type_code = v.code;")
    w("")
    w("ALTER TABLE platform_ref.document_type")
    w("    ADD CONSTRAINT document_type_cadence_values_ck")
    w("    CHECK (refresh_cadence IN ('ONE_TIME', 'PERIODIC', 'CONTINUOUS'));")
    w("")
    w("-- Mirrors document_type_scope_ck: everything we ingest is fully specified,")
    w("-- everything we do not is uniformly empty rather than defaulted.")
    w("ALTER TABLE platform_ref.document_type")
    w("    ADD CONSTRAINT document_type_cadence_scope_ck")
    w("    CHECK ((in_scope AND refresh_cadence IS NOT NULL)")
    w("        OR (NOT in_scope AND refresh_cadence IS NULL));")
    w("")

    CADENCE_PATH.write_text("\n".join(out))


def _write_field_contract(canonical: list[dict[str, str]]) -> None:
    """Emit the per-document-type field contract as its own migration.

    This is what ARCHITECTURE.md 6 means by holding the per-type column contract
    as data. The archetype tables are fixed; what a SHIPPING_BILL requires and a
    PURCHASE_REGISTER does not is a string in this column, so the twelfth
    transaction type is an INSERT rather than a schema change.
    """
    populated = [r for r in canonical if r["field_contract"]]
    out: list[str] = []
    w = out.append

    w("-- =============================================================================")
    w("-- Shared migration 009 — the per-document-type field contract.")
    w("--")
    w("-- GENERATED by scripts/gen_registry_seed.py from registry/document_types.csv.")
    w("--")
    w("-- ARCHITECTURE.md 6: the archetype tables are fixed; what varies per document")
    w("-- type lives here as data. Grammar and parser: src/silver/contract.py, which")
    w("-- the generator imports — so a contract that would be rejected at ingestion")
    w("-- cannot be committed to the CSV.")
    w("--")
    w("--     direction=OUTWARD;counterparty=OPTIONAL;doc=irn:hash64!,ack_number:text")
    w("--")
    w("-- Empty for a document type whose archetype does not read it. NOT null: the")
    w("-- absence of extra fields is a contract too, and '' parses to exactly that,")
    w("-- whereas NULL would be indistinguishable from 'nobody has filled this in'.")
    w("-- =============================================================================")
    w("")
    w("ALTER TABLE platform_ref.document_type")
    w("    ADD COLUMN IF NOT EXISTS field_contract text NOT NULL DEFAULT '';")
    w("")
    w("UPDATE platform_ref.document_type d")
    w("   SET field_contract = v.contract")
    w("  FROM (VALUES")
    w(",\n".join(
        f"    ({q(r['doc_type_code'])}, {q(r['field_contract'])})" for r in populated
    ))
    w("  ) AS v(code, contract)")
    w(" WHERE d.doc_type_code = v.code;")
    w("")
    w("-- A contract may only exist where an archetype reads one. Out-of-scope rows")
    w("-- have no ingestion path at all, so a contract on one is unreachable code in")
    w("-- table form — and unreachable code is where wrong assumptions survive.")
    w("ALTER TABLE platform_ref.document_type")
    w("    ADD CONSTRAINT document_type_field_contract_scope_ck")
    w("    CHECK (field_contract = '' OR in_scope);")
    w("")

    CONTRACT_PATH.write_text("\n".join(out))


def _write_extraction_spec(canonical: list[dict[str, str]]) -> None:
    """Emit the per-document-type PDF extraction rule as its own migration.

    Corrective refactor, 2026-08-11: this is what used to be 36 hand-written
    Python `ClassVar`-only subclasses across `src/extraction/*_types.py` —
    each pinning a `doc_type_code`, a `label_spec` dict and a fixed
    vocabulary constant as class attributes, one class per document type.
    That put a per-type extraction rule (which PDF label maps to which
    field) behind a code change and a deploy — the same defect
    `field_contract` already fixed for the Archetype 1/2 CSV contract, now
    fixed here the identical way. Grammar and parser:
    `src/extraction/spec.py`, which this generator imports — so a spec that
    would be rejected at extraction time cannot be committed to the CSV.

        authority=GSTN;fields=instrument_number:text!:"LUT ARN",validity:date_range!:"Validity"

    Empty for a document type whose archetype does not read one, and for the
    eleven narrative-contract types whose specimens have no clean
    label:value line at all (`fields=` — a real, explicit "nothing to bind"
    value, not an oversight). NOT null, same reasoning `field_contract`
    already gives: '' parses to "no fields", NULL would mean "nobody has
    filled this in yet".
    """
    populated = [r for r in canonical if r["extraction_spec"]]
    out: list[str] = []
    w = out.append

    w("-- =============================================================================")
    w("-- Shared migration 016 — the per-document-type PDF extraction spec.")
    w("--")
    w("-- GENERATED by scripts/gen_registry_seed.py from registry/document_types.csv.")
    w("--")
    w("-- Corrective refactor, 2026-08-11: replaces 36 hardcoded Python ClassVar-only")
    w("-- extractor subclasses (src/extraction/*_types.py) with data, the same fix")
    w("-- field_contract (migration 009) already applied to the Archetype 1/2 CSV")
    w("-- contract. Grammar and parser: src/extraction/spec.py, which the generator")
    w("-- imports — so a spec that would be rejected at extraction time cannot be")
    w("-- committed to the CSV.")
    w("--")
    w("--     authority=GSTN;fields=instrument_number:text!:\"LUT ARN\",")
    w("--         validity:date_range!:\"Validity\"")
    w("--")
    w("-- Empty for a document type whose archetype does not read one. NOT null: see")
    w("-- field_contract's identical reasoning (migration 009).")
    w("-- =============================================================================")
    w("")
    w("ALTER TABLE platform_ref.document_type")
    w("    ADD COLUMN IF NOT EXISTS extraction_spec text NOT NULL DEFAULT '';")
    w("")
    w("UPDATE platform_ref.document_type d")
    w("   SET extraction_spec = v.spec")
    w("  FROM (VALUES")
    w(",\n".join(
        f"    ({q(r['doc_type_code'])}, {q(r['extraction_spec'])})" for r in populated
    ))
    w("  ) AS v(code, spec)")
    w(" WHERE d.doc_type_code = v.code;")
    w("")
    w("-- Same scope guard field_contract carries: a spec on an out-of-scope row is")
    w("-- unreachable code in table form.")
    w("ALTER TABLE platform_ref.document_type")
    w("    ADD CONSTRAINT document_type_extraction_spec_scope_ck")
    w("    CHECK (extraction_spec = '' OR in_scope);")
    w("")

    EXTRACTION_SPEC_PATH.write_text("\n".join(out))


def _check_extraction_specs(canonical: list[dict[str, str]]) -> list[str]:
    """Parse every populated `extraction_spec` cell.

    Presence is not required the way `field_contract` is for archetype 1 —
    not every in-scope document type has a PDF extractor built yet (this
    batch samples 47 of them; the rest of archetypes 1/3/4/6/7/8 have no
    specimen PDF to extract from at all), so an empty cell is simply "no
    extractor for this type yet", not a gap to flag.
    """
    errors: list[str] = []
    for r in canonical:
        raw = r["extraction_spec"]
        if not raw:
            continue
        in_scope = r["stream"] != "CORPUS"
        try:
            parse_extraction_spec(raw)
        except SpecError as exc:
            errors.append(f"{r['ref']} ({r['doc_type_code']}): {exc}")
        if not in_scope:
            errors.append(
                f"{r['ref']} ({r['doc_type_code']}): out-of-scope row carries an "
                f"extraction_spec, which nothing will ever read"
            )
    return errors


def _check_contracts(canonical: list[dict[str, str]]) -> list[str]:
    """Parse every contract, and require one for every archetype-1 type.

    The presence rule is a test, not a CHECK constraint: it tightens as each
    archetype lands, and encoding "archetype 2 does not need one yet" in a
    migration would mean editing that migration when archetype 2 arrives —
    which the checksum pinning forbids.
    """
    errors: list[str] = []
    for r in canonical:
        raw = r["field_contract"]
        in_scope = r["stream"] != "CORPUS"
        archetype = r["archetype"] if in_scope else ""

        if raw:
            try:
                parse_contract(raw)
            except ContractError as exc:
                errors.append(f"{r['ref']} ({r['doc_type_code']}): {exc}")
            if not in_scope:
                errors.append(
                    f"{r['ref']} ({r['doc_type_code']}): out-of-scope row carries a "
                    f"field_contract, which nothing will ever read"
                )
        elif archetype == "1":
            errors.append(
                f"{r['ref']} ({r['doc_type_code']}): archetype 1 requires a "
                f"field_contract; the promotion path reads it to decide what is "
                f"mandatory"
            )
    return errors


def _check_table_names(canonical: list[dict[str, str]]) -> list[str]:
    """Validate `table_name`, which is the one registry column this script does
    NOT emit.

    TYPED-TABLES-PLAN.md 3: the code -> table map is catalog data, so the CSV
    stays its source of truth. But it is populated a batch at a time as each
    typed table is built, and regenerating a seed migration on every batch would
    edit a file that is already applied — which checksum pinning forbids
    (src/migrate/runner.py). So the VALUES land in the shared migration that
    accompanies each batch of tables, and this function checks the CSV side.

    The two halves are held together by
    tests/conformance/test_registry.py::test_registry_matches_reviewed_csv, which
    compares table_name in the database against this column. Adding a value here
    and forgetting the migration fails that test.
    """
    errors: list[str] = []
    seen: dict[str, list[str]] = {}
    for r in canonical:
        name = r["table_name"]
        if not name:
            continue
        if r["stream"] == "CORPUS":
            errors.append(
                f"{r['ref']} ({r['doc_type_code']}): out-of-scope row names a table "
                f"'{name}', which nothing will ever write to"
            )
        if not re.fullmatch(r"[a-z][a-z0-9_]{0,49}", name):
            errors.append(
                f"{r['ref']} ({r['doc_type_code']}): table_name '{name}' is not a "
                f"plain lowercase identifier of 50 chars or fewer"
            )
        seen.setdefault(name, []).append(r["doc_type_code"])

    # Shared tables are allowed but must be declared, not discovered. The unique
    # index on table_name was dropped in shared 013 for the marketplace reports
    # (TYPED-TABLES-PLAN.md 8, reversed 2026-08-07 on the reference schema), so
    # this is the only thing left standing between "types that genuinely share a
    # shape" and "someone pasted the wrong table name into a CSV cell".
    for name, users in sorted(seen.items()):
        if len(users) > 1 and name not in SHARED_TABLES:
            errors.append(
                f"table_name '{name}' is used by {len(users)} document types "
                f"({', '.join(sorted(users))}) but is not in SHARED_TABLES. "
                f"One table per document type unless the sharing is deliberate."
            )
    return errors


def main() -> int:
    rows = list(csv.DictReader(CSV_PATH.open()))

    umbrella = [r for r in rows if UMBRELLA_MARKER in r["notes"]]
    aliases = [r for r in rows if ALIAS_MARKER in r["notes"]]
    canonical = [r for r in rows if r not in umbrella and r not in aliases]

    # An alias row must name exactly one canonical ref, and that ref must exist.
    by_ref = {r["ref"]: r for r in rows}
    for a in aliases:
        target = a["alias_refs"]
        if target not in by_ref:
            print(f"ERROR: alias {a['ref']} names unknown ref {target}", file=sys.stderr)
            return 1
        if by_ref[target] not in canonical:
            print(f"ERROR: alias {a['ref']} points at non-canonical {target}", file=sys.stderr)
            return 1

    codes = {r["doc_type_code"] for r in canonical}
    if len(codes) != len(canonical):
        print("ERROR: duplicate doc_type_code among canonical rows", file=sys.stderr)
        return 1

    problems = (
        _check_contracts(canonical)
        + _check_table_names(canonical)
        + _check_extraction_specs(canonical)
    )
    if problems:
        for e in problems:
            print(f"ERROR: {e}", file=sys.stderr)
        return 1

    out: list[str] = []
    w = out.append

    w("-- =============================================================================")
    w("-- Shared migration 004 — Document Type Registry seed.")
    w("--")
    w("-- GENERATED by scripts/gen_registry_seed.py from registry/document_types.csv.")
    w("-- Do not edit by hand: edit the CSV and regenerate, or the reviewed source")
    w("-- and the deployed data diverge with nothing to detect it.")
    w("--")
    in_scope_n = sum(1 for r in canonical if r["stream"] != "CORPUS")
    w(f"-- {len(rows)} register refs -> {len(canonical)} document types "
      f"({in_scope_n} in scope, {len(canonical) - in_scope_n} corpus-owned).")
    w("-- =============================================================================")
    w("")
    w("-- Every document type is a universal_master value first — the FK from")
    w("-- document_type and from every tenant's artefact_ledger depends on it.")
    w("INSERT INTO platform_ref.universal_master (value_type, value, description) VALUES")
    lines = [
        f"    ('Document_Type', {q(r['doc_type_code'])}, {q(r['name'][:400])})"
        for r in canonical
    ]
    w(",\n".join(lines))
    w("ON CONFLICT (value_type, value) DO NOTHING;")
    w("")
    w("")
    w("INSERT INTO platform_ref.document_type (")
    w("    doc_type_code, name, category, grp, obligation, mode, sections,")
    w("    stream, archetype, silver_storage, source_system, in_scope, notes")
    w(") VALUES")

    lines = []
    for r in canonical:
        in_scope = r["stream"] != "CORPUS"
        stream = q(r["stream"]) if in_scope else "NULL"
        archetype = r["archetype"] if in_scope else "NULL"
        lines.append(
            f"    ({q(r['doc_type_code'])}, {q(r['name'])}, {q(r['category'])}, "
            f"{q(r['grp'])}, {q(r['obligation'])}, {q(r['mode'])}, {arr(r['sections'])}, "
            f"{stream}, {archetype}, {q(r['silver_storage'])}, {q(r['source_system'])}, "
            f"{'TRUE' if in_scope else 'FALSE'}, {q(r['notes'])})"
        )
    w(",\n".join(lines))
    w("ON CONFLICT (doc_type_code) DO NOTHING;")
    w("")
    w("")
    w("INSERT INTO platform_ref.document_type_ref"
      " (register_ref, doc_type_code, is_canonical) VALUES")

    lines = []
    for r in canonical:
        lines.append(f"    ({q(r['ref'])}, {q(r['doc_type_code'])}, TRUE)")
        # alias_refs on a canonical row: other refs for the SAME document.
        for alias_ref in (a.strip() for a in r["alias_refs"].split(",") if a.strip()):
            lines.append(f"    ({q(alias_ref)}, {q(r['doc_type_code'])}, FALSE)")
    # Alias rows emit nothing: each one's ref was already produced by its
    # canonical row's alias_refs. Emitting both would violate the PK — which is
    # the check that the two directions agree.
    for u in umbrella:
        for code_ref in (c.strip() for c in u["alias_refs"].split(",") if c.strip()):
            target = by_ref[code_ref]
            lines.append(f"    ({q(u['ref'])}, {q(target['doc_type_code'])}, FALSE)")
    w(",\n".join(lines))
    w("ON CONFLICT (register_ref, doc_type_code) DO NOTHING;")
    w("")

    OUT_PATH.write_text("\n".join(out))
    _write_cadence(canonical)
    _write_field_contract(canonical)
    _write_extraction_spec(canonical)

    n_contracts = sum(1 for r in canonical if r["field_contract"])
    n_specs = sum(1 for r in canonical if r["extraction_spec"])
    n_tables = sum(1 for r in canonical if r["table_name"])
    print(f"wrote {OUT_PATH.relative_to(ROOT)}")
    print(f"wrote {CADENCE_PATH.relative_to(ROOT)}")
    print(f"wrote {CONTRACT_PATH.relative_to(ROOT)}")
    print(f"wrote {EXTRACTION_SPEC_PATH.relative_to(ROOT)}")
    print(f"  {len(rows)} register refs")
    print(f"  {n_contracts} field contract(s)")
    print(f"  {n_specs} extraction spec(s)")
    print(f"  {n_tables} typed table(s) — checked, not emitted; see _check_table_names")
    print(f"  {len(canonical)} document types ({in_scope_n} in scope, "
          f"{len(canonical) - in_scope_n} corpus-owned)")
    print(f"  {len(umbrella)} umbrella ref(s), {len(aliases)} alias ref(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
