-- =============================================================================
-- Shared migration 009 — the per-document-type field contract.
--
-- GENERATED by scripts/gen_registry_seed.py from registry/document_types.csv.
--
-- ARCHITECTURE.md 6: the archetype tables are fixed; what varies per document
-- type lives here as data. Grammar and parser: src/silver/contract.py, which
-- the generator imports — so a contract that would be rejected at ingestion
-- cannot be committed to the CSV.
--
--     direction=OUTWARD;counterparty=OPTIONAL;doc=irn:hash64!,ack_number:text
--
-- Empty for a document type whose archetype does not read it. NOT null: the
-- absence of extra fields is a contract too, and '' parses to exactly that,
-- whereas NULL would be indistinguishable from 'nobody has filled this in'.
-- =============================================================================

ALTER TABLE platform_ref.document_type
    ADD COLUMN IF NOT EXISTS field_contract text NOT NULL DEFAULT '';

UPDATE platform_ref.document_type d
   SET field_contract = v.contract
  FROM (VALUES
    ('SALES_REGISTER', 'direction=OUTWARD;counterparty=OPTIONAL;doc=place_of_supply:text!,invoice_type:text'),
    ('CREDIT_DEBIT_NOTE_REGISTER', 'direction=OUTWARD;counterparty=OPTIONAL;doc=note_type:text!,original_doc_number:text!,original_doc_date:date!,reason:text'),
    ('PURCHASE_REGISTER', 'direction=INWARD;counterparty=REQUIRED;doc=payment_due_date:date;line=itc_eligibility:text'),
    ('HO_COMMON_INPUT_SERVICE_INVOICE', 'direction=INWARD;counterparty=REQUIRED;doc=isd_distribution_basis:text!,recipient_gstin:gstin!'),
    ('GTA_INVOICE_CONSIGNMENT_NOTE', 'direction=INWARD;counterparty=OPTIONAL;doc=consignment_note_number:text!,consignment_note_date:date!,rcm_applicable:text!'),
    ('BILL_OF_ENTRY', 'direction=INWARD;counterparty=FOREIGN;doc=be_number:text!,be_date:date!,port_code:text!;line=bcd_amount:money,social_welfare_surcharge:money'),
    ('IRN_IRP_REGISTER', 'direction=OUTWARD;counterparty=OPTIONAL;doc=irn:hash64!,ack_number:text!,ack_date:date!'),
    ('EWAY_BILL_OUTWARD_REGISTER', 'direction=OUTWARD;counterparty=OPTIONAL;doc=ewb_number:text!,ewb_date:date!,transport_mode:text,vehicle_number:text'),
    ('ICEGATE_SHIPPING_BILL', 'direction=OUTWARD;counterparty=FOREIGN;doc=shipping_bill_number:text!,shipping_bill_date:date!,port_code:text!,export_scheme:text'),
    ('ICEGATE_BILL_OF_ENTRY', 'direction=INWARD;counterparty=FOREIGN;doc=be_number:text!,be_date:date!,port_code:text!;line=bcd_amount:money,social_welfare_surcharge:money'),
    ('SEZ_BILL_OF_ENTRY', 'direction=INWARD;counterparty=REQUIRED;doc=be_number:text!,be_date:date!,sez_unit_name:text')
  ) AS v(code, contract)
 WHERE d.doc_type_code = v.code;

-- A contract may only exist where an archetype reads one. Out-of-scope rows
-- have no ingestion path at all, so a contract on one is unreachable code in
-- table form — and unreachable code is where wrong assumptions survive.
ALTER TABLE platform_ref.document_type
    ADD CONSTRAINT document_type_field_contract_scope_ck
    CHECK (field_contract = '' OR in_scope);
