-- =============================================================================
-- Shared migration 016 — the per-document-type PDF extraction spec.
--
-- GENERATED by scripts/gen_registry_seed.py from registry/document_types.csv.
--
-- Corrective refactor, 2026-08-11: replaces 36 hardcoded Python ClassVar-only
-- extractor subclasses (src/extraction/*_types.py) with data, the same fix
-- field_contract (migration 009) already applied to the Archetype 1/2 CSV
-- contract. Grammar and parser: src/extraction/spec.py, which the generator
-- imports — so a spec that would be rejected at extraction time cannot be
-- committed to the CSV.
--
--     authority=GSTN;fields=instrument_number:text!:"LUT ARN",
--         validity:date_range!:"Validity"
--
-- Empty for a document type whose archetype does not read one. NOT null: see
-- field_contract's identical reasoning (migration 009).
-- =============================================================================

ALTER TABLE platform_ref.document_type
    ADD COLUMN IF NOT EXISTS extraction_spec text NOT NULL DEFAULT '';

UPDATE platform_ref.document_type d
   SET extraction_spec = v.spec
  FROM (VALUES
    ('CERTIFICATE_OF_INCORPORATION', 'fields=reference_number:text!:"Corporate Identification Number (CIN)",as_of_date:date!:"Date of Incorporation"'),
    ('MEMORANDUM_ARTICLES_OF_ASSOCIATION', 'fields='),
    ('SHAREHOLDING_PATTERN', 'fields=reference_number:text!:"Financial Year",as_of_date:date!:"As On Date"'),
    ('RELATED_PARTY_REGISTER', 'fields=reference_number:text!:"Declared by",as_of_date:date!:"Date of Declaration"'),
    ('RELATED_PARTY_DISCLOSURE_IND_AS_24', 'fields=auditor:text!:"Auditors"'),
    ('JOINT_VENTURE_AGREEMENT', 'fields='),
    ('GSTIN_REGISTER', 'fields=reference_number:text!:"Total GSTINs under PAN",as_of_date:date!:"Register Date"'),
    ('DIRECTOR_LIST_WITH_DIN', 'fields=reference_number:text!:"Financial Years Covered",as_of_date:date!:"List Date"'),
    ('FORM_DIR_12', 'fields=reference_number:text!:"SRN",as_of_date:date!:"Date of Filing with ROC"'),
    ('BOARD_RESOLUTION_DIRECTOR_APPOINTMENT', 'fields='),
    ('DIRECTOR_SERVICE_AGREEMENT', 'fields='),
    ('KMP_LIST', 'fields=reference_number:text!:"Extracted from",as_of_date:date!:"List Date"'),
    ('COST_SHARING_AGREEMENT', 'fields='),
    ('FOREIGN_CUSTOMER_SERVICE_CONTRACT', 'fields='),
    ('OVERSEAS_VENDOR_CONTRACT', 'fields='),
    ('JOBWORK_AGREEMENT', 'fields='),
    ('LONG_DURATION_SERVICE_CONTRACT', 'fields='),
    ('TRANSFER_PRICING_DOCUMENTATION', 'fields='),
    ('ADVANCE_PRICING_AGREEMENT', 'authority=CBDT;fields=instrument_number:text!:"APA Reference No.",valid_from:date!:"Date of Signing"'),
    ('GTA_INVOICE_CONSIGNMENT_NOTE', 'fields=doc_number:text!:"Consignment Note (LR) No.",doc_date:date!:"Consignment Note Date",counterparty_gstin:gstin!:"GTA GSTIN",counterparty_name:text!:"GTA Name",taxable_value:money!:"Freight Charges",gst_amount:money!:"GST Payable under RCM"'),
    ('SECURITY_AGENCY_CONTRACT', 'fields='),
    ('LUT', 'authority=GSTN;fields=instrument_number:text!:"LUT ARN",validity:date_range!:"Validity"'),
    ('IEC_CERTIFICATE', 'authority=DGFT;fields=instrument_number:text!:"IEC Number",valid_from:date!:"Date of Issue"'),
    ('SEZ_LETTER_OF_APPROVAL', 'authority=DEV_COMMISSIONER;fields=instrument_number:text!:"LoA No.",validity:date_range!:"Validity Period"'),
    ('SEZ_LETTER_OF_PERMISSION', 'authority=DEV_COMMISSIONER;fields=instrument_number:text!:"LoP No.",validity:date_range!:"Validity Period"'),
    ('SEZ_OPERATIONS_COMMENCEMENT_CERT', 'authority=DEV_COMMISSIONER;fields=instrument_number:text!:"LoA Reference",valid_from:date!:"Commencement Date"'),
    ('SEZ_NOTIFICATION', 'authority=MIN_COMMERCE;fields=instrument_number:text!:"Notification No.",valid_from:date!:"Dated"'),
    ('SEZ_ANNUAL_PERFORMANCE_REPORT', 'authority=DEV_COMMISSIONER;fields=instrument_number:text!:"LoA Reference",valid_from:date!:"Date of Approval"'),
    ('EOU_LETTER_OF_PERMISSION', 'authority=DEV_COMMISSIONER;fields=instrument_number:text!:"LoP No.",validity:date_range!:"Validity Period"'),
    ('STPI_REGISTRATION', 'authority=STPI;fields=instrument_number:text!:"Registration No.",valid_from:date!:"Date of Registration"'),
    ('EOU_ANNUAL_COMPLIANCE_REPORT', 'authority=DEV_COMMISSIONER;fields=instrument_number:text!:"LoP Reference",valid_from:date!:"Date of Filing"'),
    ('EPCG_LICENCE', 'authority=DGFT;fields=instrument_number:text!:"EPCG Licence No.",valid_from:date!:"Date of Issue"'),
    ('ADVANCE_AUTHORISATION', 'authority=DGFT;fields=instrument_number:text!:"Advance Authorisation No.",validity:date_range!:"Validity"'),
    ('EODC', 'authority=DGFT;fields=instrument_number:text!:"EODC No.",valid_from:date!:"Date of Issue"'),
    ('SOFTEX_FORM_APPROVAL', 'authority=STPI;fields=instrument_number:text!:"SOFTEX Form No.",valid_from:date!:"Date of Certification"'),
    ('CUSTOMS_BONDED_WAREHOUSE_LICENCE', 'authority=CUSTOMS;fields=instrument_number:text!:"Licence No.",valid_from:date!:"Date of Issue"'),
    ('ITC_04_ACKNOWLEDGEMENT', 'authority=GSTN;fields=reference_number:text!:"ITC-04 Filing Reference",event_date:date!:"ITC-04 Filing Date"'),
    ('BILL_OF_ENTRY', 'fields=doc_number:text!:"Bill of Entry No.",doc_date:date!:"BoE Date",counterparty_name:text!:"Supplier",port_code:text!:"Port Code",hsn_sac:hsn!:"HSN Code",taxable_value:money!:"Assessable (Customs) Value",igst_amount:money!:"IGST"'),
    ('CUSTOMS_CLASSIFICATION_ORDER', 'authority=CUSTOMS;fields=instrument_number:text!:"Order No.",valid_from:date!:"Date of Order"'),
    ('CUSTOMS_DUTY_EXEMPTION_CERTIFICATE', 'authority=CUSTOMS;fields=instrument_number:text!:"Certificate/Notification Ref",valid_from:date!:"Date of Issue"'),
    ('B17_BOND', 'authority=CUSTOMS;fields=instrument_number:text!:"Bond No.",valid_from:date!:"Date of Execution"'),
    ('BLUT', 'authority=CUSTOMS;fields=instrument_number:text!:"BLUT No.",valid_from:date!:"Date of Execution"'),
    ('AEO_CERTIFICATE', 'authority=CUSTOMS;fields=instrument_number:text!:"AEO Certificate No.",validity:date_range!:"Validity"'),
    ('RBI_DELAYED_REALISATION_APPROVAL', 'authority=RBI;fields=instrument_number:text!:"RBI Reference No.",valid_from:date!:"Date of RBI Approval"'),
    ('RBI_COMPOUNDING_ORDER', 'authority=RBI;fields=reference_number:text!:"Compounding Application No.",event_date:date!:"Date of Compounding Order",amount:money:"Compounding Amount Paid"'),
    ('ODI_APPROVAL', 'authority=RBI;fields=instrument_number:text!:"UIN (Unique Identification Number)",valid_from:date!:"Date of Approval/Reporting Acknowledgement"'),
    ('SCOMET_LICENCE', 'authority=DGFT;fields=instrument_number:text!:"SCOMET Licence No.",validity:date_range!:"Validity"')
  ) AS v(code, spec)
 WHERE d.doc_type_code = v.code;

-- Same scope guard field_contract carries: a spec on an out-of-scope row is
-- unreachable code in table form.
ALTER TABLE platform_ref.document_type
    ADD CONSTRAINT document_type_extraction_spec_scope_ck
    CHECK (extraction_spec = '' OR in_scope);
