-- =============================================================================
-- Shared migration 035 — the published schema catalogue.
--
-- WHAT THIS IS FOR. A tenant onboarding through inafin-portal goes to the ERP
-- section, downloads the schema for the document types they must supply, maps
-- their ERP export to it, and only then uploads. These two tables are what the
-- portal renders and what `inafin-api` reads to render it.
--
-- These describe the TENANT-FACING contract — the columns an ERP export must
-- carry — not the Silver table that eventually stores it. The two differ, and
-- deliberately: a Silver row also holds `batch_id`, `row_hash`,
-- `bronze_ingest_id` and the bitemporal tail, none of which a tenant supplies
-- or should ever see. `src/silver/registers/spec.py`'s ENVELOPE_COLUMNS is the
-- set being subtracted, and it is subtracted in exactly one place:
-- `src/catalogue/document_schema.py`.
--
-- WHY A TABLE AND NOT A VIEW OVER information_schema. The obvious alternative
-- is to serve column metadata straight out of the catalog. It cannot work: the
-- Silver tables live in per-tenant schemas (t_<slug>_silver), so any such view
-- would have to pick a tenant — and the portal shows this schema BEFORE the
-- tenant has uploaded anything, sometimes before their schema even exists.
-- The catalogue is platform-level by nature, so it is platform_ref data.
--
-- HOW THE ROWS STAY HONEST. The seed (migration 036) is generated by
-- `scripts/gen_registry_seed.py` from `src/catalogue/document_schema.py`,
-- which derives every field from a loader or a registry grammar cell and never
-- invents one. `tests/conformance/test_schema_catalogue.py` then re-runs that
-- derivation against the LIVE rows and fails on any divergence — so a
-- RegisterSpec column added without a follow-up seed migration is a failing
-- test, not a wrong answer served to a tenant.
--
-- `description` is nullable and seeded empty everywhere. There is no source of
-- truth for prose field descriptions in this repo (pg_description holds zero
-- column comments across Silver), and writing 447 of them from column names
-- alone is the invented-content mistake CLAUDE.md names once already. The
-- column exists so curation has somewhere to land; it is not filled by guess.
-- =============================================================================

CREATE TABLE platform_ref.document_type_schema (
    doc_type_code text PRIMARY KEY
        REFERENCES platform_ref.document_type (doc_type_code),

    -- How the tenant supplies this type. NOT the same question as
    -- dispatch_mechanism (which loader runs) — two types can share a mechanism
    -- and differ here only in whether a column list exists to publish.
    --   TABULAR      a CSV/NDJSON export whose columns are in document_type_field
    --   DOCUMENT     the source document itself; any fields listed are what we
    --                read OUT of it, i.e. which facts it must actually show
    --   JSON         a portal/API payload uploaded exactly as the authority
    --                issued it (the GSTN returns). We do not own that shape and
    --                will not republish it as if we did — the sample file is
    --                the schema.
    --   UNSPECIFIED  in scope, but no upload path is built yet (no
    --                dispatch_mechanism). Listed rather than omitted so the
    --                portal shows the registry honestly.
    schema_kind text NOT NULL
        CHECK (schema_kind IN ('TABULAR', 'DOCUMENT', 'JSON', 'UNSPECIFIED')),

    -- How much the field list below is worth, carried rather than flattened:
    --   DERIVED   from a loader already gated against live DDL (RegisterSpec
    --             via test_register_specs.py, or sales_register.py). Cannot
    --             drift from the table without a test failing.
    --   DECLARED  from a registry grammar cell (field_contract /
    --             extraction_spec), parsed by the same parser ingestion uses.
    --   PENDING   no field list published yet. An honest empty — the portal
    --             can say "sample document only" instead of rendering a blank
    --             table and implying the type has no fields.
    provenance text NOT NULL
        CHECK (provenance IN ('DERIVED', 'DECLARED', 'PENDING'))

    -- NOTE: "PENDING implies no fields, and non-PENDING implies at least one"
    -- is a real invariant of this pair of tables, and it is NOT enforced here.
    -- It spans two tables, so a CHECK cannot express it (Postgres rejects
    -- subqueries in CHECK), and a trigger would be a second copy of a rule the
    -- generator already applies. It is asserted instead by
    -- test_schema_catalogue.py::test_pending_types_publish_no_fields, against
    -- the live rows.
);

COMMENT ON TABLE platform_ref.document_type_schema IS
    'One row per in-scope document type: how a tenant supplies it, and how '
    'trustworthy the published field list is. Seeded by migration 036, '
    'generated from src/catalogue/document_schema.py.';

CREATE TABLE platform_ref.document_type_field (
    doc_type_code text NOT NULL
        REFERENCES platform_ref.document_type_schema (doc_type_code)
        ON DELETE CASCADE,

    -- 1-based, in the order the source declares. Order is published because it
    -- is meaningful: RegisterSpec's columns are in DDL order, and row_hash —
    -- which decides whether a resubmitted row is a correction or a duplicate —
    -- is computed over that order.
    ordinal integer NOT NULL CHECK (ordinal >= 1),

    field_name text NOT NULL,

    -- ROW for a flat register; HEADER/LINE for the header/line shaped types
    -- (SALES_REGISTER and archetype 1's field_contract), where a tenant
    -- sending one flat CSV must know which columns repeat down an invoice's
    -- lines; DOCUMENT for a fact read off a PDF rather than a file column.
    scope text NOT NULL CHECK (scope IN ('ROW', 'HEADER', 'LINE', 'DOCUMENT')),

    -- The coarse kind, not the SQL domain. A tenant needs "a decimal goes
    -- here"; money_inr vs qty vs tax_rate is database-side validation, and
    -- republishing it would invite this table to disagree with the domain that
    -- actually enforces it. Same reasoning registers/spec.py's Kind gives.
    data_type text NOT NULL,

    -- The cell must carry a value. Derived by exactly one rule for the
    -- DERIVED types — required <=> NOT NULL and no DEFAULT — asserted by
    -- test_register_specs.py against the real DDL.
    required boolean NOT NULL,

    -- The literal label this field is bound to on a PDF, for
    -- extraction_spec-derived rows only. A real string off a real specimen.
    source_label text,

    -- Human prose. Always NULL today, on purpose — see this file's header.
    description text,

    PRIMARY KEY (doc_type_code, ordinal),
    CONSTRAINT document_type_field_name_uq UNIQUE (doc_type_code, scope, field_name)
);

COMMENT ON TABLE platform_ref.document_type_field IS
    'The tenant-facing field list per document type — what an ERP export must '
    'carry, NOT the Silver table''s columns. Envelope columns (batch_id, '
    'row_hash, the bitemporal tail) are subtracted; see src/catalogue/.';

CREATE INDEX document_type_field_code_idx
    ON platform_ref.document_type_field (doc_type_code);
