-- =============================================================================
-- Shared migration 042 — the field-constraint seed.
--
-- GENERATED by scripts/gen_field_constraints.py from the LIVE Silver DDL,
-- via src/catalogue/field_constraints.py. Columns and the rule table:
-- migration 041 — read its header first, it states what these values are
-- and why they are derived rather than declared.
--
-- Nothing here is hand-written. Every value traces to a pg_constraint row
-- or a pg_type/attribute fact on a real tenant schema.
--
-- DO NOT regenerate this file to fix drift — it is applied and checksum-
-- pinned. Carry the delta in a NEW migration.
-- =============================================================================

-- 181 of 352 published DERIVED fields carry at
-- least one constraint. The rest are unconstrained beyond their type and
-- their NOT NULL, which `data_type` and `required` already publish.

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'ADVANCE_RECEIPT_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.gstin',
    pattern = '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'ADVANCE_RECEIPT_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'customer_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['GOODS', 'SERVICE'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'ADVANCE_RECEIPT_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'supply_type';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.tax_rate',
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 6,
    numeric_scale = 3
  WHERE doc_type_code = 'ADVANCE_RECEIPT_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'ADVANCE_RECEIPT_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'gst_paid_on_advance';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['MTR', 'GTR', 'SSR', 'DRR', 'VRET', 'FDP', 'OTHER'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'AMAZON_MTR'
    AND scope = 'ROW'
    AND field_name = 'report_type';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'AMAZON_MTR'
    AND scope = 'ROW'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.tax_rate',
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 6,
    numeric_scale = 3
  WHERE doc_type_code = 'AMAZON_MTR'
    AND scope = 'ROW'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'AMAZON_MTR'
    AND scope = 'ROW'
    AND field_name = 'cgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'AMAZON_MTR'
    AND scope = 'ROW'
    AND field_name = 'sgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'AMAZON_MTR'
    AND scope = 'ROW'
    AND field_name = 'igst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'AMAZON_MTR'
    AND scope = 'ROW'
    AND field_name = 'tcs';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'AMAZON_MTR'
    AND scope = 'ROW'
    AND field_name = 'marketplace_fee';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'AMAZON_MTR'
    AND scope = 'ROW'
    AND field_name = 'shipping_charges';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'AMAZON_MTR'
    AND scope = 'ROW'
    AND field_name = 'net_payout';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['REVENUE', 'EXPENSE', 'OTHER'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'AUDITED_PROFIT_AND_LOSS'
    AND scope = 'ROW'
    AND field_name = 'account_type';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'AUDITED_PROFIT_AND_LOSS'
    AND scope = 'ROW'
    AND field_name = 'amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['DR', 'CR'],
    min_value = NULL,
    max_value = NULL,
    max_length = 2,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'AUDITED_PROFIT_AND_LOSS'
    AND scope = 'ROW'
    AND field_name = 'dr_cr';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['ADVANCE_FROM_CUSTOMER', 'UNBILLED_REVENUE', 'DEFERRED_REVENUE', 'CREDITOR', 'CAPITAL_GOODS', 'OTHER'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'BALANCE_SHEET'
    AND scope = 'ROW'
    AND field_name = 'category';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'BALANCE_SHEET'
    AND scope = 'ROW'
    AND field_name = 'amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'BANK_STATEMENT_INWARD_FX'
    AND scope = 'ROW'
    AND field_name = 'amount_fcy';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = 3,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'BANK_STATEMENT_INWARD_FX'
    AND scope = 'ROW'
    AND field_name = 'currency';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'BANK_STATEMENT_INWARD_FX'
    AND scope = 'ROW'
    AND field_name = 'amount_inr';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'BANK_STATEMENT_OUTWARD'
    AND scope = 'ROW'
    AND field_name = 'amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.gstin',
    pattern = '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'CONTINUOUS_SUPPLY_CONTRACT_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'customer_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'CONTINUOUS_SUPPLY_CONTRACT_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.gstin',
    pattern = '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'COST_ALLOCATION_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'from_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.gstin',
    pattern = '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'COST_ALLOCATION_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'to_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'COST_ALLOCATION_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.gstin',
    pattern = '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'CREDITOR_AGEING_REPORT'
    AND scope = 'ROW'
    AND field_name = 'supplier_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'CREDITOR_AGEING_REPORT'
    AND scope = 'ROW'
    AND field_name = 'outstanding_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 32,
    numeric_scale = 0
  WHERE doc_type_code = 'CREDITOR_AGEING_REPORT'
    AND scope = 'ROW'
    AND field_name = 'ageing_days';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['CN', 'DN'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'CREDIT_DEBIT_NOTE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'note_type';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.gstin',
    pattern = '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'CREDIT_DEBIT_NOTE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'customer_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'CREDIT_DEBIT_NOTE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'adjusted_taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.tax_rate',
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 6,
    numeric_scale = 3
  WHERE doc_type_code = 'CREDIT_DEBIT_NOTE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'CREDIT_DEBIT_NOTE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'cgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'CREDIT_DEBIT_NOTE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'sgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'CREDIT_DEBIT_NOTE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'igst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'CREDIT_DEBIT_NOTE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'cess';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'CREDIT_DEBIT_NOTE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'note_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FIXED_ASSET_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'purchase_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FIXED_ASSET_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'itc_availed';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 32,
    numeric_scale = 0
  WHERE doc_type_code = 'FIXED_ASSET_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'useful_life_months';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FIXED_ASSET_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'disposal_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['SALE', 'SCRAP', 'TRANSFER', 'WRITE_OFF', 'OTHER'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'FIXED_ASSET_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'disposal_type';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['MTR', 'GTR', 'SSR', 'DRR', 'VRET', 'FDP', 'OTHER'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'FLIPKART_GTR'
    AND scope = 'ROW'
    AND field_name = 'report_type';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FLIPKART_GTR'
    AND scope = 'ROW'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.tax_rate',
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 6,
    numeric_scale = 3
  WHERE doc_type_code = 'FLIPKART_GTR'
    AND scope = 'ROW'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FLIPKART_GTR'
    AND scope = 'ROW'
    AND field_name = 'cgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FLIPKART_GTR'
    AND scope = 'ROW'
    AND field_name = 'sgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FLIPKART_GTR'
    AND scope = 'ROW'
    AND field_name = 'igst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FLIPKART_GTR'
    AND scope = 'ROW'
    AND field_name = 'tcs';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FLIPKART_GTR'
    AND scope = 'ROW'
    AND field_name = 'marketplace_fee';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FLIPKART_GTR'
    AND scope = 'ROW'
    AND field_name = 'shipping_charges';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FLIPKART_GTR'
    AND scope = 'ROW'
    AND field_name = 'net_payout';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['MTR', 'GTR', 'SSR', 'DRR', 'VRET', 'FDP', 'OTHER'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'FOOD_DELIVERY_PARTNER_REPORT'
    AND scope = 'ROW'
    AND field_name = 'report_type';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FOOD_DELIVERY_PARTNER_REPORT'
    AND scope = 'ROW'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.tax_rate',
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 6,
    numeric_scale = 3
  WHERE doc_type_code = 'FOOD_DELIVERY_PARTNER_REPORT'
    AND scope = 'ROW'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FOOD_DELIVERY_PARTNER_REPORT'
    AND scope = 'ROW'
    AND field_name = 'cgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FOOD_DELIVERY_PARTNER_REPORT'
    AND scope = 'ROW'
    AND field_name = 'sgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FOOD_DELIVERY_PARTNER_REPORT'
    AND scope = 'ROW'
    AND field_name = 'igst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FOOD_DELIVERY_PARTNER_REPORT'
    AND scope = 'ROW'
    AND field_name = 'tcs';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FOOD_DELIVERY_PARTNER_REPORT'
    AND scope = 'ROW'
    AND field_name = 'marketplace_fee';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FOOD_DELIVERY_PARTNER_REPORT'
    AND scope = 'ROW'
    AND field_name = 'shipping_charges';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FOOD_DELIVERY_PARTNER_REPORT'
    AND scope = 'ROW'
    AND field_name = 'net_payout';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FOREIGN_CURRENCY_PAYMENT_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'amount_fcy';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = 3,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'FOREIGN_CURRENCY_PAYMENT_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'currency';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FOREIGN_CURRENCY_PAYMENT_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'amount_inr';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FORM_15CA_15CB'
    AND scope = 'ROW'
    AND field_name = 'remittance_amount_inr';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'FORM_15CA_15CB'
    AND scope = 'ROW'
    AND field_name = 'tax_withheld_inr';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.gstin',
    pattern = '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'HO_COMMON_INPUT_SERVICE_INVOICE'
    AND scope = 'ROW'
    AND field_name = 'supplier_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['RENT', 'IT', 'INSURANCE', 'AUDIT', 'OTHER'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'HO_COMMON_INPUT_SERVICE_INVOICE'
    AND scope = 'ROW'
    AND field_name = 'service_category';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'HO_COMMON_INPUT_SERVICE_INVOICE'
    AND scope = 'ROW'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.tax_rate',
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 6,
    numeric_scale = 3
  WHERE doc_type_code = 'HO_COMMON_INPUT_SERVICE_INVOICE'
    AND scope = 'ROW'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'HO_COMMON_INPUT_SERVICE_INVOICE'
    AND scope = 'ROW'
    AND field_name = 'cgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'HO_COMMON_INPUT_SERVICE_INVOICE'
    AND scope = 'ROW'
    AND field_name = 'sgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'HO_COMMON_INPUT_SERVICE_INVOICE'
    AND scope = 'ROW'
    AND field_name = 'igst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.gstin',
    pattern = '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'INTER_GSTIN_TRANSACTION_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'from_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.gstin',
    pattern = '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'INTER_GSTIN_TRANSACTION_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'to_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['STOCK_TRANSFER', 'CROSS_CHARGE', 'CAPITAL_GOOD_TRANSFER', 'OTHER'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'INTER_GSTIN_TRANSACTION_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'txn_type';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'INTER_GSTIN_TRANSACTION_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.tax_rate',
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 6,
    numeric_scale = 3
  WHERE doc_type_code = 'INTER_GSTIN_TRANSACTION_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'INTER_GSTIN_TRANSACTION_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'cgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'INTER_GSTIN_TRANSACTION_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'sgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'INTER_GSTIN_TRANSACTION_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'igst';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['RULE_42', 'RULE_43', 'SEC_17_5', 'OTHER'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'ITC_REVERSAL_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'reversal_type';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'ITC_REVERSAL_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'cgst_reversed';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'ITC_REVERSAL_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'sgst_reversed';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'ITC_REVERSAL_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'igst_reversed';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'ITC_REVERSAL_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'cess_reversed';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.qty',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 3
  WHERE doc_type_code = 'JOBWORK_DISPATCH_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'qty';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'JOBWORK_DISPATCH_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.gstin',
    pattern = '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'JOBWORK_DISPATCH_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'job_worker_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['MTR', 'GTR', 'SSR', 'DRR', 'VRET', 'FDP', 'OTHER'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'MARKETPLACE_DISBURSEMENT_DRR'
    AND scope = 'ROW'
    AND field_name = 'report_type';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_DISBURSEMENT_DRR'
    AND scope = 'ROW'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.tax_rate',
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 6,
    numeric_scale = 3
  WHERE doc_type_code = 'MARKETPLACE_DISBURSEMENT_DRR'
    AND scope = 'ROW'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_DISBURSEMENT_DRR'
    AND scope = 'ROW'
    AND field_name = 'cgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_DISBURSEMENT_DRR'
    AND scope = 'ROW'
    AND field_name = 'sgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_DISBURSEMENT_DRR'
    AND scope = 'ROW'
    AND field_name = 'igst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_DISBURSEMENT_DRR'
    AND scope = 'ROW'
    AND field_name = 'tcs';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_DISBURSEMENT_DRR'
    AND scope = 'ROW'
    AND field_name = 'marketplace_fee';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_DISBURSEMENT_DRR'
    AND scope = 'ROW'
    AND field_name = 'shipping_charges';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_DISBURSEMENT_DRR'
    AND scope = 'ROW'
    AND field_name = 'net_payout';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['MTR', 'GTR', 'SSR', 'DRR', 'VRET', 'FDP', 'OTHER'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'MARKETPLACE_RETURNS_VRET'
    AND scope = 'ROW'
    AND field_name = 'report_type';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_RETURNS_VRET'
    AND scope = 'ROW'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.tax_rate',
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 6,
    numeric_scale = 3
  WHERE doc_type_code = 'MARKETPLACE_RETURNS_VRET'
    AND scope = 'ROW'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_RETURNS_VRET'
    AND scope = 'ROW'
    AND field_name = 'cgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_RETURNS_VRET'
    AND scope = 'ROW'
    AND field_name = 'sgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_RETURNS_VRET'
    AND scope = 'ROW'
    AND field_name = 'igst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_RETURNS_VRET'
    AND scope = 'ROW'
    AND field_name = 'tcs';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_RETURNS_VRET'
    AND scope = 'ROW'
    AND field_name = 'marketplace_fee';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_RETURNS_VRET'
    AND scope = 'ROW'
    AND field_name = 'shipping_charges';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_RETURNS_VRET'
    AND scope = 'ROW'
    AND field_name = 'net_payout';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['MTR', 'GTR', 'SSR', 'DRR', 'VRET', 'FDP', 'OTHER'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'MARKETPLACE_SETTLEMENT_SSR'
    AND scope = 'ROW'
    AND field_name = 'report_type';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_SETTLEMENT_SSR'
    AND scope = 'ROW'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.tax_rate',
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 6,
    numeric_scale = 3
  WHERE doc_type_code = 'MARKETPLACE_SETTLEMENT_SSR'
    AND scope = 'ROW'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_SETTLEMENT_SSR'
    AND scope = 'ROW'
    AND field_name = 'cgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_SETTLEMENT_SSR'
    AND scope = 'ROW'
    AND field_name = 'sgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_SETTLEMENT_SSR'
    AND scope = 'ROW'
    AND field_name = 'igst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_SETTLEMENT_SSR'
    AND scope = 'ROW'
    AND field_name = 'tcs';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_SETTLEMENT_SSR'
    AND scope = 'ROW'
    AND field_name = 'marketplace_fee';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_SETTLEMENT_SSR'
    AND scope = 'ROW'
    AND field_name = 'shipping_charges';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'MARKETPLACE_SETTLEMENT_SSR'
    AND scope = 'ROW'
    AND field_name = 'net_payout';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['MTR', 'GTR', 'SSR', 'DRR', 'VRET', 'FDP', 'OTHER'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'OTHER_MARKETPLACE_SETTLEMENT'
    AND scope = 'ROW'
    AND field_name = 'report_type';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'OTHER_MARKETPLACE_SETTLEMENT'
    AND scope = 'ROW'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.tax_rate',
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 6,
    numeric_scale = 3
  WHERE doc_type_code = 'OTHER_MARKETPLACE_SETTLEMENT'
    AND scope = 'ROW'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'OTHER_MARKETPLACE_SETTLEMENT'
    AND scope = 'ROW'
    AND field_name = 'cgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'OTHER_MARKETPLACE_SETTLEMENT'
    AND scope = 'ROW'
    AND field_name = 'sgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'OTHER_MARKETPLACE_SETTLEMENT'
    AND scope = 'ROW'
    AND field_name = 'igst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'OTHER_MARKETPLACE_SETTLEMENT'
    AND scope = 'ROW'
    AND field_name = 'tcs';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'OTHER_MARKETPLACE_SETTLEMENT'
    AND scope = 'ROW'
    AND field_name = 'marketplace_fee';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'OTHER_MARKETPLACE_SETTLEMENT'
    AND scope = 'ROW'
    AND field_name = 'shipping_charges';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'OTHER_MARKETPLACE_SETTLEMENT'
    AND scope = 'ROW'
    AND field_name = 'net_payout';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'PAYROLL_TDS_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'gross_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'PAYROLL_TDS_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'tds_deducted';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.gstin',
    pattern = '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'PURCHASE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'supplier_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'PURCHASE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.tax_rate',
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 6,
    numeric_scale = 3
  WHERE doc_type_code = 'PURCHASE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'PURCHASE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'cgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'PURCHASE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'sgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'PURCHASE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'igst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'PURCHASE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'cess';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['ELIGIBLE', 'INELIGIBLE', 'BLOCKED', 'PARTIAL'],
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'PURCHASE_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'itc_eligibility';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.gstin',
    pattern = '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'RCM_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'supplier_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'RCM_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.tax_rate',
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 6,
    numeric_scale = 3
  WHERE doc_type_code = 'RCM_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'RCM_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'rcm_liability';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'RCM_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'cgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'RCM_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'sgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'RCM_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'igst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.gstin',
    pattern = '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'customer_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = '^[0-9]{2}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'place_of_supply';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = 3,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'currency';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'trade_discount';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'freight';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'packing';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'insurance';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = 1,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 32,
    numeric_scale = 0
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'line_number';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = '^[0-9]{4,8}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'hsn_sac';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.qty',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 3
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'qty';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 4
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'unit_price';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.tax_rate',
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 6,
    numeric_scale = 3
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'cgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'sgst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'igst';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'cess';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'SALES_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'total_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'SKU_MASTER'
    AND scope = 'ROW'
    AND field_name = 'declared_mrp';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.qty',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 3
  WHERE doc_type_code = 'STOCK_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'opening_qty';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.qty',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 3
  WHERE doc_type_code = 'STOCK_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'closing_qty';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.qty',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 3
  WHERE doc_type_code = 'STOCK_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'write_off_qty';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'STOCK_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'write_off_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'SUPPLIER_PAYMENT_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.gstin',
    pattern = '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'SUPPLIER_PAYMENT_REGISTER'
    AND scope = 'ROW'
    AND field_name = 'supplier_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'TRIAL_BALANCE'
    AND scope = 'ROW'
    AND field_name = 'opening_balance';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'TRIAL_BALANCE'
    AND scope = 'ROW'
    AND field_name = 'closing_balance';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = ARRAY['DR', 'CR'],
    min_value = NULL,
    max_value = NULL,
    max_length = 2,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'TRIAL_BALANCE'
    AND scope = 'ROW'
    AND field_name = 'dr_cr';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.gstin',
    pattern = '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL
  WHERE doc_type_code = 'UNBILLED_REVENUE_SCHEDULE'
    AND scope = 'ROW'
    AND field_name = 'customer_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = 'platform_ref.money_inr',
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2
  WHERE doc_type_code = 'UNBILLED_REVENUE_SCHEDULE'
    AND scope = 'ROW'
    AND field_name = 'amount';

INSERT INTO platform_ref.document_type_rule
    (doc_type_code, constraint_name, expression, columns)
VALUES
    ('SALES_REGISTER', 'sales_register_line_tax_head', '((COALESCE((igst), (0)) > (0)) AND (COALESCE((cgst), (0)) = (0)) AND (COALESCE((sgst), (0)) = (0))) OR (COALESCE((igst), (0)) = (0))', ARRAY['igst', 'cgst', 'sgst'])
;
