-- =============================================================================
-- Shared migration 043 — correct five PDF_EXTRACTION types the catalogue
-- published as TABULAR.
--
-- THE BUG, found by the ERP upload E2E suite (2026-09-01, sixteenth session)
-- against schema release `v3`. `src/catalogue/document_schema.py`'s
-- `derive_document_schema` picked a source by "which one is non-empty" rather
-- than by `dispatch_mechanism` — so a type carrying a LEFTOVER `RegisterSpec`
-- or `field_contract` cell from a superseded design published `TABULAR` even
-- when `platform_ref.document_type.dispatch_mechanism` said `PDF_EXTRACTION`
-- and `src/dispatch/router.py` was actually going to hand the upload to
-- `pypdf`. A tenant who filled in the published CSV contract for
-- `BILL_OF_ENTRY` had it handed to `pypdf`, which is not a CSV reader, and
-- got `pypdf.errors.PdfStreamError` wrapped in an opaque HTTP 500.
--
-- Five types, all confirmed by re-running the (now corrected) derivation
-- against live `platform_ref.document_type` and diffing every one of the 125
-- in-scope rows against what was seeded — these five are the ONLY rows that
-- move; zero collateral, zero errors elsewhere:
--
--   FIRC_BRC_REGISTER, FORM_15CA_15CB, PAYROLL_TDS_REGISTER
--       Archetype 2 — bespoke per-type PDF table extractors
--       (`src/extraction/register_types.py`, tenant migration `020`). Each
--       carries a `RegisterSpec`/Silver table because that is where its
--       extractor WRITES, not because a tenant uploads CSV against it. None
--       has an `extraction_spec` (archetype 2 is not label:value-shaped —
--       `src/extraction/registry.py`'s module docstring says so), so the
--       honest published shape is PENDING/DOCUMENT: no declared field list,
--       send the PDF.
--   BILL_OF_ENTRY, GTA_INVOICE_CONSIGNMENT_NOTE
--       Archetype 1 PDF extractors (`src/extraction/transaction_types.py`).
--       Each carries a vestigial `field_contract` cell alongside its real
--       `extraction_spec`; DOCUMENT/DECLARED from the `extraction_spec` is
--       what a tenant should see.
--
-- THE DERIVATION ITSELF WAS FIXED FIRST, in the same commit as this file —
-- `dispatch_mechanism` is now the resolution order, not a fallback consulted
-- only when every other source is empty. This migration is the DATA
-- correction that follows from that code fix, generated by running the
-- corrected `derive_document_schema` against each of these five rows and
-- transcribing its output — not hand-typed. Migration `036` (the original
-- seed) is untouched: it is applied and checksum-pinned, and this is exactly
-- the kind of delta `CLAUDE.md` calls for instead of regenerating it.
--
-- ALSO CLOSED, defense in depth, same commit: `PypdfReader.extract` now
-- catches `pypdf.errors.PyPdfError` and raises a typed `UnreadablePdfError`
-- (`ValueError` subclass) instead of letting it escape as an opaque 500 —
-- covers a genuinely corrupt/truncated PDF for a real `PDF_EXTRACTION` type,
-- which this migration's fix does not, since it is not a catalogue problem.
-- =============================================================================

UPDATE platform_ref.document_type_schema SET schema_kind = 'DOCUMENT',
    provenance = 'DECLARED' WHERE doc_type_code = 'BILL_OF_ENTRY';
UPDATE platform_ref.document_type_schema SET schema_kind = 'DOCUMENT',
    provenance = 'PENDING' WHERE doc_type_code = 'FIRC_BRC_REGISTER';
UPDATE platform_ref.document_type_schema SET schema_kind = 'DOCUMENT',
    provenance = 'PENDING' WHERE doc_type_code = 'FORM_15CA_15CB';
UPDATE platform_ref.document_type_schema SET schema_kind = 'DOCUMENT',
    provenance = 'DECLARED' WHERE doc_type_code = 'GTA_INVOICE_CONSIGNMENT_NOTE';
UPDATE platform_ref.document_type_schema SET schema_kind = 'DOCUMENT',
    provenance = 'PENDING' WHERE doc_type_code = 'PAYROLL_TDS_REGISTER';

-- The old TABULAR field lists (RegisterSpec columns for three of these,
-- field_contract attributes for the other two) described a CSV shape none of
-- these five types will ever actually receive. Deleted outright rather than
-- updated in place: the new field set for BILL_OF_ENTRY/
-- GTA_INVOICE_CONSIGNMENT_NOTE has different names, a different scope
-- (DOCUMENT, not HEADER/LINE/ROW) and a different length, so there is no
-- row-for-row correspondence to UPDATE onto.
DELETE FROM platform_ref.document_type_field WHERE doc_type_code = ANY(ARRAY[
    'BILL_OF_ENTRY',
    'FIRC_BRC_REGISTER',
    'FORM_15CA_15CB',
    'GTA_INVOICE_CONSIGNMENT_NOTE',
    'PAYROLL_TDS_REGISTER'
]);

-- Only two of the five get a field list back — see the header. The other
-- three (FIRC_BRC_REGISTER, FORM_15CA_15CB, PAYROLL_TDS_REGISTER) correctly
-- have none: PENDING means exactly that, an honest empty.
INSERT INTO platform_ref.document_type_field
    (doc_type_code, ordinal, field_name, scope, data_type, required, source_label)
VALUES
    ('BILL_OF_ENTRY', 1, 'doc_number', 'DOCUMENT', 'text', TRUE, 'Bill of Entry No.'),
    ('BILL_OF_ENTRY', 2, 'doc_date', 'DOCUMENT', 'date', TRUE, 'BoE Date'),
    ('BILL_OF_ENTRY', 3, 'counterparty_name', 'DOCUMENT', 'text', TRUE, 'Supplier'),
    ('BILL_OF_ENTRY', 4, 'port_code', 'DOCUMENT', 'text', TRUE, 'Port Code'),
    ('BILL_OF_ENTRY', 5, 'hsn_sac', 'DOCUMENT', 'hsn', TRUE, 'HSN Code'),
    ('BILL_OF_ENTRY', 6, 'taxable_value', 'DOCUMENT', 'money', TRUE, 'Assessable (Customs) Value'),
    ('BILL_OF_ENTRY', 7, 'igst_amount', 'DOCUMENT', 'money', TRUE, 'IGST'),
    ('GTA_INVOICE_CONSIGNMENT_NOTE', 1, 'doc_number', 'DOCUMENT', 'text', TRUE, 'Consignment Note (LR) No.'),
    ('GTA_INVOICE_CONSIGNMENT_NOTE', 2, 'doc_date', 'DOCUMENT', 'date', TRUE, 'Consignment Note Date'),
    ('GTA_INVOICE_CONSIGNMENT_NOTE', 3, 'counterparty_gstin', 'DOCUMENT', 'gstin', TRUE, 'GTA GSTIN'),
    ('GTA_INVOICE_CONSIGNMENT_NOTE', 4, 'counterparty_name', 'DOCUMENT', 'text', TRUE, 'GTA Name'),
    ('GTA_INVOICE_CONSIGNMENT_NOTE', 5, 'taxable_value', 'DOCUMENT', 'money', TRUE, 'Freight Charges'),
    ('GTA_INVOICE_CONSIGNMENT_NOTE', 6, 'gst_amount', 'DOCUMENT', 'money', TRUE, 'GST Payable under RCM');
