-- =============================================================================
-- Shared migration 046 — ARCHETYPE1_PROMOTE types publish their fixed
-- envelope columns, not only their per-type additions.
--
-- THE BUG, found by the ERP upload E2E suite (2026-09-01): the published
-- schema for every ARCHETYPE1_PROMOTE type (`EWAY_BILL_OUTWARD_REGISTER`,
-- `ICEGATE_BILL_OF_ENTRY`, `ICEGATE_SHIPPING_BILL`, `IRN_IRP_REGISTER`,
-- `SEZ_BILL_OF_ENTRY` — the entire in-scope set for this mechanism) named
-- only the columns each type's `field_contract` cell ADDS on top of the
-- archetype's fixed shape, because `field_contract`'s own docstring says
-- that is all it describes ("what one document type adds to the archetype's
-- fixed shape"). But `src/silver/validate.py::validate_transaction_csv` —
-- what every one of these types is actually loaded through — always demands
-- `doc_number`, `doc_date`, `line_number`, `hsn_sac`, `quantity`,
-- `unit_price`, `taxable_value`, `gst_rate` (`REQUIRED_COLUMNS`) plus a
-- counterparty column decided by `Counterparty`, and none of that fixed
-- shape was ever published. A conforming upload against the OLD published
-- schema — the per-type additions alone — would have been missing eight or
-- more mandatory columns and rejected outright.
--
-- THE CODE FIX, same commit: `src/catalogue/document_schema.py`'s
-- `_from_field_contract` now emits the fixed envelope (read off
-- `validate.py`'s own `REQUIRED_COLUMNS` and `Counterparty` handling, not
-- restated by hand) ahead of each type's per-type additions, at both grains.
-- This migration is the DATA correction that follows, generated by running
-- the corrected derivation against these five live registry rows and
-- transcribing its output — not hand-typed. Migration `036` (the original
-- seed) is untouched: applied and checksum-pinned.
--
-- `document_type_schema` needs no change here — `schema_kind`/`provenance`
-- were already correct (TABULAR/DECLARED); only the field LIST was
-- incomplete.
-- =============================================================================

DELETE FROM platform_ref.document_type_field WHERE doc_type_code = ANY(ARRAY[
    'EWAY_BILL_OUTWARD_REGISTER',
    'ICEGATE_BILL_OF_ENTRY',
    'ICEGATE_SHIPPING_BILL',
    'IRN_IRP_REGISTER',
    'SEZ_BILL_OF_ENTRY'
]);

INSERT INTO platform_ref.document_type_field
    (doc_type_code, ordinal, field_name, scope, data_type, required)
VALUES
    ('EWAY_BILL_OUTWARD_REGISTER', 1, 'doc_number', 'HEADER', 'text', TRUE),
    ('EWAY_BILL_OUTWARD_REGISTER', 2, 'doc_date', 'HEADER', 'date', TRUE),
    ('EWAY_BILL_OUTWARD_REGISTER', 3, 'currency', 'HEADER', 'text', FALSE),
    ('EWAY_BILL_OUTWARD_REGISTER', 4, 'counterparty_gstin', 'HEADER', 'text', FALSE),
    ('EWAY_BILL_OUTWARD_REGISTER', 5, 'counterparty_name', 'HEADER', 'text', FALSE),
    ('EWAY_BILL_OUTWARD_REGISTER', 6, 'ewb_number', 'HEADER', 'text', TRUE),
    ('EWAY_BILL_OUTWARD_REGISTER', 7, 'ewb_date', 'HEADER', 'date', TRUE),
    ('EWAY_BILL_OUTWARD_REGISTER', 8, 'transport_mode', 'HEADER', 'text', FALSE),
    ('EWAY_BILL_OUTWARD_REGISTER', 9, 'vehicle_number', 'HEADER', 'text', FALSE),
    ('EWAY_BILL_OUTWARD_REGISTER', 10, 'line_number', 'LINE', 'integer', TRUE),
    ('EWAY_BILL_OUTWARD_REGISTER', 11, 'hsn_sac', 'LINE', 'text', TRUE),
    ('EWAY_BILL_OUTWARD_REGISTER', 12, 'description', 'LINE', 'text', FALSE),
    ('EWAY_BILL_OUTWARD_REGISTER', 13, 'quantity', 'LINE', 'decimal', TRUE),
    ('EWAY_BILL_OUTWARD_REGISTER', 14, 'uom', 'LINE', 'text', FALSE),
    ('EWAY_BILL_OUTWARD_REGISTER', 15, 'unit_price', 'LINE', 'decimal', TRUE),
    ('EWAY_BILL_OUTWARD_REGISTER', 16, 'taxable_value', 'LINE', 'decimal', TRUE),
    ('EWAY_BILL_OUTWARD_REGISTER', 17, 'gst_rate', 'LINE', 'decimal', TRUE),
    ('EWAY_BILL_OUTWARD_REGISTER', 18, 'cgst_amount', 'LINE', 'decimal', FALSE),
    ('EWAY_BILL_OUTWARD_REGISTER', 19, 'sgst_amount', 'LINE', 'decimal', FALSE),
    ('EWAY_BILL_OUTWARD_REGISTER', 20, 'igst_amount', 'LINE', 'decimal', FALSE),
    ('EWAY_BILL_OUTWARD_REGISTER', 21, 'cess_amount', 'LINE', 'decimal', FALSE),
    ('EWAY_BILL_OUTWARD_REGISTER', 22, 'itc_amount', 'LINE', 'decimal', FALSE),
    ('ICEGATE_BILL_OF_ENTRY', 1, 'doc_number', 'HEADER', 'text', TRUE),
    ('ICEGATE_BILL_OF_ENTRY', 2, 'doc_date', 'HEADER', 'date', TRUE),
    ('ICEGATE_BILL_OF_ENTRY', 3, 'currency', 'HEADER', 'text', FALSE),
    ('ICEGATE_BILL_OF_ENTRY', 4, 'counterparty_name', 'HEADER', 'text', TRUE),
    ('ICEGATE_BILL_OF_ENTRY', 5, 'be_number', 'HEADER', 'text', TRUE),
    ('ICEGATE_BILL_OF_ENTRY', 6, 'be_date', 'HEADER', 'date', TRUE),
    ('ICEGATE_BILL_OF_ENTRY', 7, 'port_code', 'HEADER', 'text', TRUE),
    ('ICEGATE_BILL_OF_ENTRY', 8, 'line_number', 'LINE', 'integer', TRUE),
    ('ICEGATE_BILL_OF_ENTRY', 9, 'hsn_sac', 'LINE', 'text', TRUE),
    ('ICEGATE_BILL_OF_ENTRY', 10, 'description', 'LINE', 'text', FALSE),
    ('ICEGATE_BILL_OF_ENTRY', 11, 'quantity', 'LINE', 'decimal', TRUE),
    ('ICEGATE_BILL_OF_ENTRY', 12, 'uom', 'LINE', 'text', FALSE),
    ('ICEGATE_BILL_OF_ENTRY', 13, 'unit_price', 'LINE', 'decimal', TRUE),
    ('ICEGATE_BILL_OF_ENTRY', 14, 'taxable_value', 'LINE', 'decimal', TRUE),
    ('ICEGATE_BILL_OF_ENTRY', 15, 'gst_rate', 'LINE', 'decimal', TRUE),
    ('ICEGATE_BILL_OF_ENTRY', 16, 'cgst_amount', 'LINE', 'decimal', FALSE),
    ('ICEGATE_BILL_OF_ENTRY', 17, 'sgst_amount', 'LINE', 'decimal', FALSE),
    ('ICEGATE_BILL_OF_ENTRY', 18, 'igst_amount', 'LINE', 'decimal', FALSE),
    ('ICEGATE_BILL_OF_ENTRY', 19, 'cess_amount', 'LINE', 'decimal', FALSE),
    ('ICEGATE_BILL_OF_ENTRY', 20, 'itc_amount', 'LINE', 'decimal', FALSE),
    ('ICEGATE_BILL_OF_ENTRY', 21, 'bcd_amount', 'LINE', 'money', FALSE),
    ('ICEGATE_BILL_OF_ENTRY', 22, 'social_welfare_surcharge', 'LINE', 'money', FALSE),
    ('ICEGATE_SHIPPING_BILL', 1, 'doc_number', 'HEADER', 'text', TRUE),
    ('ICEGATE_SHIPPING_BILL', 2, 'doc_date', 'HEADER', 'date', TRUE),
    ('ICEGATE_SHIPPING_BILL', 3, 'currency', 'HEADER', 'text', FALSE),
    ('ICEGATE_SHIPPING_BILL', 4, 'counterparty_name', 'HEADER', 'text', TRUE),
    ('ICEGATE_SHIPPING_BILL', 5, 'shipping_bill_number', 'HEADER', 'text', TRUE),
    ('ICEGATE_SHIPPING_BILL', 6, 'shipping_bill_date', 'HEADER', 'date', TRUE),
    ('ICEGATE_SHIPPING_BILL', 7, 'port_code', 'HEADER', 'text', TRUE),
    ('ICEGATE_SHIPPING_BILL', 8, 'export_scheme', 'HEADER', 'text', FALSE),
    ('ICEGATE_SHIPPING_BILL', 9, 'line_number', 'LINE', 'integer', TRUE),
    ('ICEGATE_SHIPPING_BILL', 10, 'hsn_sac', 'LINE', 'text', TRUE),
    ('ICEGATE_SHIPPING_BILL', 11, 'description', 'LINE', 'text', FALSE),
    ('ICEGATE_SHIPPING_BILL', 12, 'quantity', 'LINE', 'decimal', TRUE),
    ('ICEGATE_SHIPPING_BILL', 13, 'uom', 'LINE', 'text', FALSE),
    ('ICEGATE_SHIPPING_BILL', 14, 'unit_price', 'LINE', 'decimal', TRUE),
    ('ICEGATE_SHIPPING_BILL', 15, 'taxable_value', 'LINE', 'decimal', TRUE),
    ('ICEGATE_SHIPPING_BILL', 16, 'gst_rate', 'LINE', 'decimal', TRUE),
    ('ICEGATE_SHIPPING_BILL', 17, 'cgst_amount', 'LINE', 'decimal', FALSE),
    ('ICEGATE_SHIPPING_BILL', 18, 'sgst_amount', 'LINE', 'decimal', FALSE),
    ('ICEGATE_SHIPPING_BILL', 19, 'igst_amount', 'LINE', 'decimal', FALSE),
    ('ICEGATE_SHIPPING_BILL', 20, 'cess_amount', 'LINE', 'decimal', FALSE),
    ('ICEGATE_SHIPPING_BILL', 21, 'itc_amount', 'LINE', 'decimal', FALSE),
    ('IRN_IRP_REGISTER', 1, 'doc_number', 'HEADER', 'text', TRUE),
    ('IRN_IRP_REGISTER', 2, 'doc_date', 'HEADER', 'date', TRUE),
    ('IRN_IRP_REGISTER', 3, 'currency', 'HEADER', 'text', FALSE),
    ('IRN_IRP_REGISTER', 4, 'counterparty_gstin', 'HEADER', 'text', FALSE),
    ('IRN_IRP_REGISTER', 5, 'counterparty_name', 'HEADER', 'text', FALSE),
    ('IRN_IRP_REGISTER', 6, 'irn', 'HEADER', 'hash64', TRUE),
    ('IRN_IRP_REGISTER', 7, 'ack_number', 'HEADER', 'text', TRUE),
    ('IRN_IRP_REGISTER', 8, 'ack_date', 'HEADER', 'date', TRUE),
    ('IRN_IRP_REGISTER', 9, 'line_number', 'LINE', 'integer', TRUE),
    ('IRN_IRP_REGISTER', 10, 'hsn_sac', 'LINE', 'text', TRUE),
    ('IRN_IRP_REGISTER', 11, 'description', 'LINE', 'text', FALSE),
    ('IRN_IRP_REGISTER', 12, 'quantity', 'LINE', 'decimal', TRUE),
    ('IRN_IRP_REGISTER', 13, 'uom', 'LINE', 'text', FALSE),
    ('IRN_IRP_REGISTER', 14, 'unit_price', 'LINE', 'decimal', TRUE),
    ('IRN_IRP_REGISTER', 15, 'taxable_value', 'LINE', 'decimal', TRUE),
    ('IRN_IRP_REGISTER', 16, 'gst_rate', 'LINE', 'decimal', TRUE),
    ('IRN_IRP_REGISTER', 17, 'cgst_amount', 'LINE', 'decimal', FALSE),
    ('IRN_IRP_REGISTER', 18, 'sgst_amount', 'LINE', 'decimal', FALSE),
    ('IRN_IRP_REGISTER', 19, 'igst_amount', 'LINE', 'decimal', FALSE),
    ('IRN_IRP_REGISTER', 20, 'cess_amount', 'LINE', 'decimal', FALSE),
    ('IRN_IRP_REGISTER', 21, 'itc_amount', 'LINE', 'decimal', FALSE),
    ('SEZ_BILL_OF_ENTRY', 1, 'doc_number', 'HEADER', 'text', TRUE),
    ('SEZ_BILL_OF_ENTRY', 2, 'doc_date', 'HEADER', 'date', TRUE),
    ('SEZ_BILL_OF_ENTRY', 3, 'currency', 'HEADER', 'text', FALSE),
    ('SEZ_BILL_OF_ENTRY', 4, 'counterparty_gstin', 'HEADER', 'text', TRUE),
    ('SEZ_BILL_OF_ENTRY', 5, 'counterparty_name', 'HEADER', 'text', FALSE),
    ('SEZ_BILL_OF_ENTRY', 6, 'be_number', 'HEADER', 'text', TRUE),
    ('SEZ_BILL_OF_ENTRY', 7, 'be_date', 'HEADER', 'date', TRUE),
    ('SEZ_BILL_OF_ENTRY', 8, 'sez_unit_name', 'HEADER', 'text', FALSE),
    ('SEZ_BILL_OF_ENTRY', 9, 'line_number', 'LINE', 'integer', TRUE),
    ('SEZ_BILL_OF_ENTRY', 10, 'hsn_sac', 'LINE', 'text', TRUE),
    ('SEZ_BILL_OF_ENTRY', 11, 'description', 'LINE', 'text', FALSE),
    ('SEZ_BILL_OF_ENTRY', 12, 'quantity', 'LINE', 'decimal', TRUE),
    ('SEZ_BILL_OF_ENTRY', 13, 'uom', 'LINE', 'text', FALSE),
    ('SEZ_BILL_OF_ENTRY', 14, 'unit_price', 'LINE', 'decimal', TRUE),
    ('SEZ_BILL_OF_ENTRY', 15, 'taxable_value', 'LINE', 'decimal', TRUE),
    ('SEZ_BILL_OF_ENTRY', 16, 'gst_rate', 'LINE', 'decimal', TRUE),
    ('SEZ_BILL_OF_ENTRY', 17, 'cgst_amount', 'LINE', 'decimal', FALSE),
    ('SEZ_BILL_OF_ENTRY', 18, 'sgst_amount', 'LINE', 'decimal', FALSE),
    ('SEZ_BILL_OF_ENTRY', 19, 'igst_amount', 'LINE', 'decimal', FALSE),
    ('SEZ_BILL_OF_ENTRY', 20, 'cess_amount', 'LINE', 'decimal', FALSE),
    ('SEZ_BILL_OF_ENTRY', 21, 'itc_amount', 'LINE', 'decimal', FALSE)
;
