-- =============================================================================
-- Shared migration 047 — ARCHETYPE1_PROMOTE's fixed envelope columns publish
-- real field constraints and their cross-field tax-head rule.
--
-- THE GAP, found by a follow-up ERP upload E2E audit against v5 (2026-09-02):
-- `field_constraints.py`'s derivation was gated to `provenance = 'DERIVED'`,
-- so `EWAY_BILL_OUTWARD_REGISTER`, `ICEGATE_BILL_OF_ENTRY`,
-- `ICEGATE_SHIPPING_BILL`, `IRN_IRP_REGISTER`, `SEZ_BILL_OF_ENTRY` — all
-- DECLARED, because their PER-TYPE additions come from a `field_contract`
-- cell — published NO constraints at all, even for their FIXED envelope
-- columns (`hsn_sac`, `gst_rate`, `line_number`, `counterparty_gstin`, ...),
-- which are real, typed columns on the shared `transaction_document`/
-- `transaction_line` tables (tenant migration 007) and carry the exact same
-- kind of CHECK/domain/tax-head rule `SALES_REGISTER`'s equivalent columns
-- already published. A client generating an export against the OLD
-- constraint-free schema had no way to learn `gst_rate` is bounded 0-100,
-- `hsn_sac` must be 4-8 digits, or that IGST and CGST/SGST cannot both be
-- non-zero on one line — the same class of refusal-at-ingestion gap shared
-- migration 041's header names, just missed for this one DECLARED-but-
-- table-backed mechanism.
--
-- THE CODE FIX, same commit: `field_constraints.py`'s `_PUBLISHED_FIELDS`
-- now also selects ARCHETYPE1_PROMOTE fields, and a new `_relation` helper
-- resolves their column to the shared `transaction_document`/
-- `transaction_line` tables by SCOPE (`document_type.table_name` is NULL for
-- these five — they share one pair of tables, not one each). Each type's
-- PER-TYPE additions (`be_number`, `sez_unit_name`, ...) still publish no
-- constraint — they land in a jsonb `attributes` column with nothing to
-- derive, exactly as before; `test_declared_types_publish_no_constraints`
-- now documents ARCHETYPE1_PROMOTE as the one exception rather than
-- asserting a blanket "no DECLARED type ever carries one".
--
-- WHAT MOVES: 83 `document_type_field` rows (constraint columns for the
-- fixed envelope across all five types) and 5 new `document_type_rule` rows
-- — `transaction_line_tax_head` (IGST positive implies CGST/SGST zero),
-- the archetype-1 table's own version of `sales_register_line_tax_head`,
-- already published for `SALES_REGISTER` since shared migration 042.
-- Generated by re-running the derivation against live DDL and diffing
-- against what was seeded; migration 045/046 are untouched.
-- =============================================================================

-- 83 rows updated.

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'doc_number';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'date'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'doc_date';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'currency';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = '^[0-9]{2}[A-Z0-9]{13}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'counterparty_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'counterparty_name';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = 1,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 32,
    numeric_scale = 0,
    sql_type = 'integer'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'line_number';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = '^[0-9]{4,8}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'hsn_sac';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'description';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 3,
    sql_type = 'numeric'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'quantity';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 4,
    sql_type = 'numeric'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'unit_price';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 5,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'cgst_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'sgst_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'igst_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'cess_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'EWAY_BILL_OUTWARD_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'itc_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'HEADER'
    AND field_name = 'doc_number';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'date'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'HEADER'
    AND field_name = 'doc_date';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'HEADER'
    AND field_name = 'currency';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'HEADER'
    AND field_name = 'counterparty_name';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = 1,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 32,
    numeric_scale = 0,
    sql_type = 'integer'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'line_number';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = '^[0-9]{4,8}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'hsn_sac';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'description';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 3,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'quantity';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 4,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'unit_price';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 5,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'cgst_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'sgst_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'igst_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'cess_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'itc_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'HEADER'
    AND field_name = 'doc_number';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'date'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'HEADER'
    AND field_name = 'doc_date';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'HEADER'
    AND field_name = 'currency';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'HEADER'
    AND field_name = 'counterparty_name';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = 1,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 32,
    numeric_scale = 0,
    sql_type = 'integer'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'LINE'
    AND field_name = 'line_number';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = '^[0-9]{4,8}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'LINE'
    AND field_name = 'hsn_sac';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'LINE'
    AND field_name = 'description';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 3,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'LINE'
    AND field_name = 'quantity';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 4,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'LINE'
    AND field_name = 'unit_price';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'LINE'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 5,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'LINE'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'LINE'
    AND field_name = 'cgst_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'LINE'
    AND field_name = 'sgst_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'LINE'
    AND field_name = 'igst_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'LINE'
    AND field_name = 'cess_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'ICEGATE_SHIPPING_BILL'
    AND scope = 'LINE'
    AND field_name = 'itc_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'doc_number';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'date'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'doc_date';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'currency';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = '^[0-9]{2}[A-Z0-9]{13}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'counterparty_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'HEADER'
    AND field_name = 'counterparty_name';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = 1,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 32,
    numeric_scale = 0,
    sql_type = 'integer'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'line_number';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = '^[0-9]{4,8}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'hsn_sac';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'description';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 3,
    sql_type = 'numeric'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'quantity';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 4,
    sql_type = 'numeric'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'unit_price';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 5,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'cgst_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'sgst_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'igst_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'cess_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'IRN_IRP_REGISTER'
    AND scope = 'LINE'
    AND field_name = 'itc_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'HEADER'
    AND field_name = 'doc_number';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'date'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'HEADER'
    AND field_name = 'doc_date';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'HEADER'
    AND field_name = 'currency';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = '^[0-9]{2}[A-Z0-9]{13}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'HEADER'
    AND field_name = 'counterparty_gstin';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'HEADER'
    AND field_name = 'counterparty_name';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = 1,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 32,
    numeric_scale = 0,
    sql_type = 'integer'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'line_number';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = '^[0-9]{4,8}$',
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'hsn_sac';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = NULL,
    numeric_scale = NULL,
    sql_type = 'text'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'description';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 3,
    sql_type = 'numeric'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'quantity';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 4,
    sql_type = 'numeric'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'unit_price';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'taxable_value';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = 0,
    max_value = 100,
    max_length = NULL,
    numeric_precision = 5,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'gst_rate';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'cgst_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'sgst_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'igst_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'cess_amount';

UPDATE platform_ref.document_type_field SET
    sql_domain = NULL,
    pattern = NULL,
    allowed_values = NULL,
    min_value = NULL,
    max_value = NULL,
    max_length = NULL,
    numeric_precision = 18,
    numeric_scale = 2,
    sql_type = 'numeric'
  WHERE doc_type_code = 'SEZ_BILL_OF_ENTRY'
    AND scope = 'LINE'
    AND field_name = 'itc_amount';

INSERT INTO platform_ref.document_type_rule
    (doc_type_code, constraint_name, expression, columns)
VALUES
    ('EWAY_BILL_OUTWARD_REGISTER', 'transaction_line_tax_head', '((igst_amount > (0)) AND (cgst_amount = (0)) AND (sgst_amount = (0))) OR (igst_amount = (0))', ARRAY['igst_amount', 'cgst_amount', 'sgst_amount']),
    ('ICEGATE_BILL_OF_ENTRY', 'transaction_line_tax_head', '((igst_amount > (0)) AND (cgst_amount = (0)) AND (sgst_amount = (0))) OR (igst_amount = (0))', ARRAY['igst_amount', 'cgst_amount', 'sgst_amount']),
    ('ICEGATE_SHIPPING_BILL', 'transaction_line_tax_head', '((igst_amount > (0)) AND (cgst_amount = (0)) AND (sgst_amount = (0))) OR (igst_amount = (0))', ARRAY['igst_amount', 'cgst_amount', 'sgst_amount']),
    ('IRN_IRP_REGISTER', 'transaction_line_tax_head', '((igst_amount > (0)) AND (cgst_amount = (0)) AND (sgst_amount = (0))) OR (igst_amount = (0))', ARRAY['igst_amount', 'cgst_amount', 'sgst_amount']),
    ('SEZ_BILL_OF_ENTRY', 'transaction_line_tax_head', '((igst_amount > (0)) AND (cgst_amount = (0)) AND (sgst_amount = (0))) OR (igst_amount = (0))', ARRAY['igst_amount', 'cgst_amount', 'sgst_amount'])
;
